// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_mux_bin_array with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_mux_bin_array_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [63:0] o_out;
  logic [1:0] o_out_valid;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_valid);
  end

  // lfsr rotated by 17*i in word i, so a stimulus window may wrap past bit 63.
  logic [575:0] lfsr_x;
  assign lfsr_x = {{lfsr[55:0], lfsr[63:56]}, {lfsr[8:0], lfsr[63:9]}, {lfsr[25:0], lfsr[63:26]}, {lfsr[42:0], lfsr[63:43]}, {lfsr[59:0], lfsr[63:60]}, {lfsr[12:0], lfsr[63:13]}, {lfsr[29:0], lfsr[63:30]}, {lfsr[46:0], lfsr[63:47]}, lfsr};

  br_mux_bin_array dut (
    .select(lfsr[7:0]),
    .in(lfsr_x[519:8]),
    .out(o_out),
    .out_valid(o_out_valid)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
