// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_demux_addr_decode with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_demux_addr_decode_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [3:0] o_select_onehot;
  logic [63:0] o_downstream_addr_out;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_select_onehot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_addr_out);
  end

  br_demux_addr_decode dut (
    .clk(clk),
    .rst(rst),
    .addr_valid(lfsr[0]),
    .upstream_addr(lfsr[16:1]),
    .downstream_addr_base({17'd0, lfsr[63:17]}),
    .downstream_addr_size({17'd0, lfsr[63:17]}),
    .downstream_addr_in({17'd0, lfsr[63:17]}),
    .select_onehot(o_select_onehot),
    .downstream_addr_out(o_downstream_addr_out)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
