// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_flow_demux_select_unstable with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_flow_demux_select_unstable_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_push_ready;
  logic [3:0] o_pop_valid_unstable;
  logic [127:0] o_pop_data_unstable;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid_unstable);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data_unstable);
  end

  br_flow_demux_select_unstable dut (
    .clk(clk),
    .rst(rst),
    .select(lfsr[1:0]),
    .push_valid(lfsr[2]),
    .push_data(lfsr[34:3]),
    .pop_ready(lfsr[38:35]),
    .push_ready(o_push_ready),
    .pop_valid_unstable(o_pop_valid_unstable),
    .pop_data_unstable(o_pop_data_unstable)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
