// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_csr_axil_widget with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_csr_axil_widget_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_axil_awready;
  logic [0:0] o_axil_wready;
  logic [0:0] o_axil_bvalid;
  logic [1:0] o_axil_bresp;
  logic [0:0] o_axil_arready;
  logic [0:0] o_axil_rvalid;
  logic [31:0] o_axil_rdata;
  logic [1:0] o_axil_rresp;
  logic [0:0] o_csr_req_valid;
  logic [0:0] o_csr_req_write;
  logic [15:0] o_csr_req_addr;
  logic [31:0] o_csr_req_wdata;
  logic [3:0] o_csr_req_wstrb;
  logic [0:0] o_csr_req_secure;
  logic [0:0] o_csr_req_privileged;
  logic [0:0] o_csr_req_abort;
  logic [0:0] o_request_aborted;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_write);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_secure);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_privileged);
      acc = {acc[62:0], acc[63]} ^ 64'(o_csr_req_abort);
      acc = {acc[62:0], acc[63]} ^ 64'(o_request_aborted);
  end

  br_csr_axil_widget #(
    .AddrWidth(16),
    .DataWidth(32),
    .MaxTimeoutCycles(100),
    .RegisterCsrRequestOutputs(0),
    .RegisterResponseOutputs(0)
  ) dut (
    .clk(clk),
    .rst(rst),
    .axil_awvalid(lfsr[0]),
    .axil_awaddr(lfsr[16:1]),
    .axil_awprot(lfsr[19:17]),
    .axil_wvalid(lfsr[20]),
    .axil_wdata(lfsr[52:21]),
    .axil_wstrb(lfsr[56:53]),
    .axil_bready(lfsr[57]),
    .axil_arvalid(lfsr[58]),
    .axil_araddr({11'd0, lfsr[63:59]}),
    .axil_arprot(lfsr[13:11]),
    .axil_rready(lfsr[14]),
    .csr_resp_valid(lfsr[15]),
    .csr_resp_rdata(lfsr[47:16]),
    .csr_resp_slverr(lfsr[48]),
    .csr_resp_decerr(lfsr[49]),
    .timeout_enable(lfsr[50]),
    .timeout_cycles(lfsr[57:51]),
    .axil_awready(o_axil_awready),
    .axil_wready(o_axil_wready),
    .axil_bvalid(o_axil_bvalid),
    .axil_bresp(o_axil_bresp),
    .axil_arready(o_axil_arready),
    .axil_rvalid(o_axil_rvalid),
    .axil_rdata(o_axil_rdata),
    .axil_rresp(o_axil_rresp),
    .csr_req_valid(o_csr_req_valid),
    .csr_req_write(o_csr_req_write),
    .csr_req_addr(o_csr_req_addr),
    .csr_req_wdata(o_csr_req_wdata),
    .csr_req_wstrb(o_csr_req_wstrb),
    .csr_req_secure(o_csr_req_secure),
    .csr_req_privileged(o_csr_req_privileged),
    .csr_req_abort(o_csr_req_abort),
    .request_aborted(o_request_aborted)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
