// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_ram_initializer with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_ram_initializer_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_busy;
  logic [0:0] o_wr_valid;
  logic [3:0] o_wr_addr;
  logic [31:0] o_wr_data;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_busy);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wr_data);
  end

  br_ram_initializer #(
    .Depth(16),
    .Width(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .initial_value(lfsr[31:0]),
    .start(lfsr[32]),
    .busy(o_busy),
    .wr_valid(o_wr_valid),
    .wr_addr(o_wr_addr),
    .wr_data(o_wr_data)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
