// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_fifo_shared_pop_ctrl with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_fifo_shared_pop_ctrl_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [1:0] o_head_ready;
  logic [1:0] o_bypass_ready;
  logic [1:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [1:0] o_pop_empty;
  logic [1:0] o_dealloc_valid;
  logic [9:0] o_dealloc_entry_id;
  logic [1:0] o_data_ram_rd_addr_valid;
  logic [9:0] o_data_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_head_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_bypass_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dealloc_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dealloc_entry_id);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_rd_addr);
  end

  br_fifo_shared_pop_ctrl dut (
    .clk(clk),
    .rst(rst),
    .head_valid(lfsr[1:0]),
    .head(lfsr[11:2]),
    .ram_empty(lfsr[13:12]),
    .ram_items(lfsr[25:14]),
    .bypass_valid_unstable(lfsr[27:26]),
    .bypass_data_unstable({28'd0, lfsr[63:28]}),
    .pop_ready(lfsr[29:28]),
    .data_ram_rd_data_valid(lfsr[31:30]),
    .data_ram_rd_data({32'd0, lfsr[63:32]}),
    .head_ready(o_head_ready),
    .bypass_ready(o_bypass_ready),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_empty(o_pop_empty),
    .dealloc_valid(o_dealloc_valid),
    .dealloc_entry_id(o_dealloc_entry_id),
    .data_ram_rd_addr_valid(o_data_ram_rd_addr_valid),
    .data_ram_rd_addr(o_data_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
