// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_ram_addr_decoder with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_ram_addr_decoder_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [3:0] o_out_valid;
  logic [11:0] o_out_addr;
  logic [3:0] o_out_data_valid;
  logic [127:0] o_out_data;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_data_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_data);
  end

  br_ram_addr_decoder #(
    .DataWidth(32),
    .Depth(32),
    .EnableDatapath(0),
    .Stages(0),
    .Tiles(4)
  ) dut (
    .clk(clk),
    .rst(rst),
    .in_valid(lfsr[0]),
    .in_addr(lfsr[5:1]),
    .in_data_valid(lfsr[6]),
    .in_data(lfsr[38:7]),
    .out_valid(o_out_valid),
    .out_addr(o_out_addr),
    .out_data_valid(o_out_data_valid),
    .out_data(o_out_data)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
