// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_cdc_fifo_ctrl_1r1w with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_cdc_fifo_ctrl_1r1w_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_push_ready;
  logic [0:0] o_push_full;
  logic [5:0] o_push_slots;
  logic [0:0] o_push_ram_wr_valid;
  logic [4:0] o_push_ram_wr_addr;
  logic [63:0] o_push_ram_wr_data;
  logic [0:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [0:0] o_pop_empty;
  logic [5:0] o_pop_items;
  logic [0:0] o_pop_ram_rd_addr_valid;
  logic [4:0] o_pop_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_full);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_slots);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_items);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_ram_rd_addr);
  end

  br_cdc_fifo_ctrl_1r1w dut (
    .push_clk(clk),
    .pop_clk(clk),
    .push_rst(rst),
    .pop_rst(rst),
    .push_valid(lfsr[0]),
    .push_data({1'd0, lfsr[63:1]}),
    .pop_ready(lfsr[1]),
    .pop_ram_rd_data_valid(lfsr[2]),
    .pop_ram_rd_data({3'd0, lfsr[63:3]}),
    .push_ready(o_push_ready),
    .push_full(o_push_full),
    .push_slots(o_push_slots),
    .push_ram_wr_valid(o_push_ram_wr_valid),
    .push_ram_wr_addr(o_push_ram_wr_addr),
    .push_ram_wr_data(o_push_ram_wr_data),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_empty(o_pop_empty),
    .pop_items(o_pop_items),
    .pop_ram_rd_addr_valid(o_pop_ram_rd_addr_valid),
    .pop_ram_rd_addr(o_pop_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
