// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_tracker_reorder_buffer_flops with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_tracker_reorder_buffer_flops_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_alloc_valid;
  logic [3:0] o_alloc_entry_id;
  logic [0:0] o_reordered_resp_pop_valid;
  logic [31:0] o_reordered_resp_pop_data;
  logic [0:0] o_resp_pending;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_alloc_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_alloc_entry_id);
      acc = {acc[62:0], acc[63]} ^ 64'(o_reordered_resp_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_reordered_resp_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_resp_pending);
  end

  br_tracker_reorder_buffer_flops #(
    .DataWidth(32),
    .EntryIdWidth(4),
    .NumEntries(16),
    .RegisterPopOutputs(0)
  ) dut (
    .clk(clk),
    .rst(rst),
    .alloc_ready(lfsr[0]),
    .unordered_resp_push_valid(lfsr[1]),
    .unordered_resp_push_entry_id(lfsr[5:2]),
    .unordered_resp_push_data(lfsr[37:6]),
    .reordered_resp_pop_ready(lfsr[38]),
    .alloc_valid(o_alloc_valid),
    .alloc_entry_id(o_alloc_entry_id),
    .reordered_resp_pop_valid(o_reordered_resp_pop_valid),
    .reordered_resp_pop_data(o_reordered_resp_pop_data),
    .resp_pending(o_resp_pending)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
