// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_lfsr with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_lfsr_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_out;
  logic [31:0] o_out_state;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_state);
  end

  br_lfsr #(
    .AdvanceSteps(1),
    .Width(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .reinit(lfsr[0]),
    .initial_state(lfsr[32:1]),
    .taps({1'd0, lfsr[63:33]}),
    .advance(lfsr[1]),
    .out(o_out),
    .out_state(o_out_state)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
