// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_credit_counter with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_credit_counter_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [3:0] o_value;
  logic [0:0] o_decr_ready;
  logic [3:0] o_available;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_value);
      acc = {acc[62:0], acc[63]} ^ 64'(o_decr_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_available);
  end

  br_credit_counter dut (
    .clk(clk),
    .rst(rst),
    .incr_valid(lfsr[0]),
    .incr(lfsr[1]),
    .decr_valid(lfsr[2]),
    .decr(lfsr[3]),
    .initial_value(lfsr[7:4]),
    .withhold(lfsr[11:8]),
    .value(o_value),
    .decr_ready(o_decr_ready),
    .available(o_available)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
