// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_arb_grant_hold with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_arb_grant_hold_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_enable_priority_update_to_arb;
  logic [15:0] o_grant;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_enable_priority_update_to_arb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_grant);
  end

  br_arb_grant_hold #(
    .NumRequesters(16)
  ) dut (
    .clk(clk),
    .rst(rst),
    .grant_hold(lfsr[15:0]),
    .enable_grant_hold_update(lfsr[16]),
    .grant_from_arb(lfsr[32:17]),
    .enable_priority_update_to_arb(o_enable_priority_update_to_arb),
    .grant(o_grant)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
