// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axil_default_target with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axil_default_target_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_target_awready;
  logic [0:0] o_target_wready;
  logic [1:0] o_target_bresp;
  logic [0:0] o_target_bvalid;
  logic [0:0] o_target_arready;
  logic [31:0] o_target_rdata;
  logic [1:0] o_target_rresp;
  logic [0:0] o_target_rvalid;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rvalid);
  end

  br_amba_axil_default_target dut (
    .clk(clk),
    .rst(rst),
    .target_awvalid(lfsr[0]),
    .target_wvalid(lfsr[1]),
    .target_bready(lfsr[2]),
    .target_arvalid(lfsr[3]),
    .target_rready(lfsr[4]),
    .target_awready(o_target_awready),
    .target_wready(o_target_wready),
    .target_bresp(o_target_bresp),
    .target_bvalid(o_target_bvalid),
    .target_arready(o_target_arready),
    .target_rdata(o_target_rdata),
    .target_rresp(o_target_rresp),
    .target_rvalid(o_target_rvalid)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
