// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps MulAddSgn with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module MulAddSgn_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [47:0] o_P;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_P);
  end

  // lfsr rotated by 17*i in word i, so a stimulus window may wrap past bit 63.
  logic [127:0] lfsr_x;
  assign lfsr_x = {{lfsr[46:0], lfsr[63:47]}, lfsr};

  MulAddSgn dut (
    .X(lfsr[23:0]),
    .Y(lfsr[47:24]),
    .A(lfsr_x[95:48]),
    .P(o_P)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
