// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_multi_xfer_reg_fwd with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_multi_xfer_reg_fwd_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [1:0] o_push_receivable;
  logic [1:0] o_pop_sendable;
  logic [63:0] o_pop_data;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_receivable);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_sendable);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
  end

  br_multi_xfer_reg_fwd #(
    .NumSymbols(2),
    .SymbolWidth(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .push_sendable(lfsr[1:0]),
    .push_data({2'd0, lfsr[63:2]}),
    .pop_receivable(lfsr[3:2]),
    .push_receivable(o_push_receivable),
    .pop_sendable(o_pop_sendable),
    .pop_data(o_pop_data)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
