// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axi2axil with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axi2axil_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_axi_awready;
  logic [0:0] o_axi_wready;
  logic [3:0] o_axi_bid;
  logic [7:0] o_axi_buser;
  logic [1:0] o_axi_bresp;
  logic [0:0] o_axi_bvalid;
  logic [0:0] o_axi_arready;
  logic [3:0] o_axi_rid;
  logic [31:0] o_axi_rdata;
  logic [7:0] o_axi_ruser;
  logic [1:0] o_axi_rresp;
  logic [0:0] o_axi_rlast;
  logic [0:0] o_axi_rvalid;
  logic [31:0] o_axil_awaddr;
  logic [2:0] o_axil_awprot;
  logic [7:0] o_axil_awuser;
  logic [0:0] o_axil_awvalid;
  logic [31:0] o_axil_wdata;
  logic [3:0] o_axil_wstrb;
  logic [7:0] o_axil_wuser;
  logic [0:0] o_axil_wvalid;
  logic [0:0] o_axil_bready;
  logic [31:0] o_axil_araddr;
  logic [2:0] o_axil_arprot;
  logic [7:0] o_axil_aruser;
  logic [0:0] o_axil_arvalid;
  logic [0:0] o_axil_rready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_bid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_buser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_rid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_ruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_rlast);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axi_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_bready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_araddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_arprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_aruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_arvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_axil_rready);
  end

  br_amba_axi2axil dut (
    .clk(clk),
    .rst(rst),
    .axi_awaddr(lfsr[31:0]),
    .axi_awid(lfsr[35:32]),
    .axi_awlen(lfsr[43:36]),
    .axi_awsize(lfsr[46:44]),
    .axi_awburst(lfsr[48:47]),
    .axi_awprot(lfsr[51:49]),
    .axi_awuser(lfsr[59:52]),
    .axi_awvalid(lfsr[60]),
    .axi_wdata({29'd0, lfsr[63:61]}),
    .axi_wstrb(lfsr[32:29]),
    .axi_wuser(lfsr[40:33]),
    .axi_wlast(lfsr[41]),
    .axi_wvalid(lfsr[42]),
    .axi_bready(lfsr[43]),
    .axi_araddr({12'd0, lfsr[63:44]}),
    .axi_arid(lfsr[15:12]),
    .axi_arlen(lfsr[23:16]),
    .axi_arsize(lfsr[26:24]),
    .axi_arburst(lfsr[28:27]),
    .axi_arprot(lfsr[31:29]),
    .axi_aruser(lfsr[39:32]),
    .axi_arvalid(lfsr[40]),
    .axi_rready(lfsr[41]),
    .axil_awready(lfsr[42]),
    .axil_wready(lfsr[43]),
    .axil_bresp(lfsr[45:44]),
    .axil_buser(lfsr[53:46]),
    .axil_bvalid(lfsr[54]),
    .axil_arready(lfsr[55]),
    .axil_rdata({24'd0, lfsr[63:56]}),
    .axil_rresp(lfsr[25:24]),
    .axil_ruser(lfsr[33:26]),
    .axil_rvalid(lfsr[34]),
    .axi_awready(o_axi_awready),
    .axi_wready(o_axi_wready),
    .axi_bid(o_axi_bid),
    .axi_buser(o_axi_buser),
    .axi_bresp(o_axi_bresp),
    .axi_bvalid(o_axi_bvalid),
    .axi_arready(o_axi_arready),
    .axi_rid(o_axi_rid),
    .axi_rdata(o_axi_rdata),
    .axi_ruser(o_axi_ruser),
    .axi_rresp(o_axi_rresp),
    .axi_rlast(o_axi_rlast),
    .axi_rvalid(o_axi_rvalid),
    .axil_awaddr(o_axil_awaddr),
    .axil_awprot(o_axil_awprot),
    .axil_awuser(o_axil_awuser),
    .axil_awvalid(o_axil_awvalid),
    .axil_wdata(o_axil_wdata),
    .axil_wstrb(o_axil_wstrb),
    .axil_wuser(o_axil_wuser),
    .axil_wvalid(o_axil_wvalid),
    .axil_bready(o_axil_bready),
    .axil_araddr(o_axil_araddr),
    .axil_arprot(o_axil_arprot),
    .axil_aruser(o_axil_aruser),
    .axil_arvalid(o_axil_arvalid),
    .axil_rready(o_axil_rready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
