// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_ram_flops_1r1w_mock with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_ram_flops_1r1w_mock_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_rd_data_valid;
  logic [31:0] o_rd_data;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_rd_data_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_rd_data);
  end

  br_ram_flops_1r1w_mock dut (
    .wr_clk(clk),
    .rd_clk(clk),
    .wr_rst(rst),
    .rd_rst(rst),
    .wr_valid(lfsr[0]),
    .wr_addr(lfsr[4:1]),
    .wr_data(lfsr[36:5]),
    .wr_word_en(lfsr[37]),
    .rd_addr_valid(lfsr[38]),
    .rd_addr(lfsr[42:39]),
    .rd_data_valid(o_rd_data_valid),
    .rd_data(o_rd_data)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
