// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps FmaShare with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module FmaShare_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [27:0] o_res_c;
  logic [27:0] o_res_d;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_res_c);
      acc = {acc[62:0], acc[63]} ^ 64'(o_res_d);
  end

  FmaShare dut (
    .a(lfsr[13:0]),
    .b(lfsr[27:14]),
    .c(lfsr[41:28]),
    .d(lfsr[55:42]),
    .res_c(o_res_c),
    .res_d(o_res_d)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
