# One source per line, in compile order. Read by slang, verilator and yosys.
# Macro headers travel with the source: slang resolves an include relative
# to the including file, verilator only searches its -I list, and both front
# ends must see the same files.
br_credit_counter.sv
br_delay_valid.sv
br_math_pkg.sv
br_enc_onehot2bin.sv
br_demux_bin.sv
br_misc_unused.sv
br_flow_checks_valid_data_impl.sv
br_flow_checks_valid_data_intg.sv
br_flow_demux_select_unstable.sv
br_flow_arb_core.sv
br_mux_onehot.sv
br_flow_mux_core.sv
br_fifo_shared_read_xbar.sv
br_flow_join_select_multihot.sv
br_flow_join.sv
br_fifo_shared_pop_ctrl_credit_ext_arbiter.sv
br_arb_pairwise_core_internal.sv
br_lru_state_internal.sv
br_arb_lru_internal.sv
br_fifo_shared_pop_ctrl_credit.sv
br_counter.sv
br_delay_shift_reg.sv
br_enc_countones.sv
br_enc_priority_encoder.sv
br_shift_rotate.sv
br_tracker_linked_list_ctrl.sv
br_fifo_shared_dynamic_ptr_mgr.sv
br_enc_priority_dynamic.sv
br_mux_bin.sv
br_arb_multi_rr.sv
br_multi_xfer_checks_sendable_data_intg.sv
br_misc_tieoff_one.sv
br_misc_tieoff_zero.sv
br_multi_xfer_distributor_core.sv
br_multi_xfer_distributor_rr.sv
br_delay.sv
br_enc_bin2onehot.sv
br_flow_reg_fwd.sv
br_multi_xfer_checks_sendable_data_impl.sv
br_shift_left.sv
br_shift_right.sv
br_multi_xfer_reg_fwd.sv
br_tracker_freelist.sv
br_fifo_shared_dynamic_push_ctrl.sv
br_credit_receiver.sv
br_delay_nr.sv
br_fifo_shared_dynamic_push_ctrl_credit.sv
br_fifo_shared_dynamic_ctrl_push_credit_pop_credit.sv
br_ram_addr_decoder.sv
br_ram_data_rd_pipe.sv
br_ram_flops_tile.sv
br_ram_flops.sv
br_fifo_shared_dynamic_flops_push_credit_pop_credit.sv
