// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_tracker_linked_list_ctrl with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_tracker_linked_list_ctrl_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_head_valid;
  logic [6:0] o_head;
  logic [0:0] o_empty;
  logic [7:0] o_items;
  logic [3:0] o_ptr_ram_wr_valid;
  logic [27:0] o_ptr_ram_wr_addr;
  logic [27:0] o_ptr_ram_wr_data;
  logic [0:0] o_ptr_ram_rd_addr_valid;
  logic [6:0] o_ptr_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_head_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_head);
      acc = {acc[62:0], acc[63]} ^ 64'(o_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_items);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_rd_addr);
  end

  br_tracker_linked_list_ctrl #(
    .Depth(128),
    .NumLinkedLists(4),
    .NumWritePorts(4),
    .RamReadLatency(2)
  ) dut (
    .clk(clk),
    .rst(rst),
    .next_tail_valid(lfsr[3:0]),
    .next_tail(lfsr[31:4]),
    .head_ready(lfsr[32]),
    .ptr_ram_rd_data_valid(lfsr[33]),
    .ptr_ram_rd_data(lfsr[40:34]),
    .head_valid(o_head_valid),
    .head(o_head),
    .empty(o_empty),
    .items(o_items),
    .ptr_ram_wr_valid(o_ptr_ram_wr_valid),
    .ptr_ram_wr_addr(o_ptr_ram_wr_addr),
    .ptr_ram_wr_data(o_ptr_ram_wr_data),
    .ptr_ram_rd_addr_valid(o_ptr_ram_rd_addr_valid),
    .ptr_ram_rd_addr(o_ptr_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
