// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_tracker_reorder with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_tracker_reorder_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_alloc_valid;
  logic [3:0] o_alloc_entry_id;
  logic [0:0] o_dealloc_complete_valid;
  logic [3:0] o_dealloc_complete_entry_id;
  logic [4:0] o_free_entry_count;
  logic [4:0] o_allocated_entry_count;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_alloc_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_alloc_entry_id);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dealloc_complete_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dealloc_complete_entry_id);
      acc = {acc[62:0], acc[63]} ^ 64'(o_free_entry_count);
      acc = {acc[62:0], acc[63]} ^ 64'(o_allocated_entry_count);
  end

  br_tracker_reorder dut (
    .clk(clk),
    .rst(rst),
    .alloc_ready(lfsr[0]),
    .dealloc_valid(lfsr[1]),
    .dealloc_entry_id(lfsr[5:2]),
    .dealloc_complete_ready(lfsr[6]),
    .alloc_valid(o_alloc_valid),
    .alloc_entry_id(o_alloc_entry_id),
    .dealloc_complete_valid(o_dealloc_complete_valid),
    .dealloc_complete_entry_id(o_dealloc_complete_entry_id),
    .free_entry_count(o_free_entry_count),
    .allocated_entry_count(o_allocated_entry_count)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
