// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_delay_shift_reg with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_delay_shift_reg_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [63:0] o_value;
  logic [63:0] o_shift_out;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_value);
      acc = {acc[62:0], acc[63]} ^ 64'(o_shift_out);
  end

  br_delay_shift_reg dut (
    .clk(clk),
    .rst(rst),
    .reinit(lfsr[0]),
    .initial_value({1'd0, lfsr[63:1]}),
    .shift_en(lfsr[1]),
    .shift_in({2'd0, lfsr[63:2]}),
    .value(o_value),
    .shift_out(o_shift_out)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
