// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_credit_receiver with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_credit_receiver_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_push_receiver_in_reset;
  logic [2:0] o_push_credit;
  logic [3:0] o_pop_valid;
  logic [255:0] o_pop_data;
  logic [4:0] o_credit_count;
  logic [4:0] o_credit_available;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_receiver_in_reset);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_credit);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_count);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_available);
  end

  br_credit_receiver #(
    .MaxCredit(16),
    .NumFlows(4),
    .PopCreditMaxChange(4),
    .PushCreditMaxChange(4),
    .RegisterPushOutputs(1),
    .Width(64)
  ) dut (
    .clk(clk),
    .rst(rst),
    .push_sender_in_reset(rst),
    .push_receiver_in_reset(rst),
    .push_credit_stall(lfsr[0]),
    .push_valid(lfsr[4:1]),
    .push_data({197'd0, lfsr[63:5]}),
    .pop_credit(lfsr[7:5]),
    .credit_initial(lfsr[12:8]),
    .credit_withhold(lfsr[17:13]),
    .push_receiver_in_reset(o_push_receiver_in_reset),
    .push_credit(o_push_credit),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .credit_count(o_credit_count),
    .credit_available(o_credit_available)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
