// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_cdc_fifo_ctrl_pop_1r1w with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_cdc_fifo_ctrl_pop_1r1w_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_pop_reset_active_pop;
  logic [5:0] o_pop_pop_count_gray;
  logic [0:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [0:0] o_pop_empty;
  logic [5:0] o_pop_items;
  logic [0:0] o_pop_ram_rd_addr_valid;
  logic [4:0] o_pop_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_reset_active_pop);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_pop_count_gray);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_items);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_ram_rd_addr);
  end

  br_cdc_fifo_ctrl_pop_1r1w dut (
    .push_clk(clk),
    .pop_clk(clk),
    .push_rst(rst),
    .pop_rst(rst),
    .push_push_count_gray(lfsr[5:0]),
    .push_reset_active_push(lfsr[6]),
    .pop_ready(lfsr[7]),
    .pop_ram_rd_data_valid(lfsr[8]),
    .pop_ram_rd_data({9'd0, lfsr[63:9]}),
    .pop_reset_active_pop(o_pop_reset_active_pop),
    .pop_pop_count_gray(o_pop_pop_count_gray),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_empty(o_pop_empty),
    .pop_items(o_pop_items),
    .pop_ram_rd_addr_valid(o_pop_ram_rd_addr_valid),
    .pop_ram_rd_addr(o_pop_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
