// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_fifo_shared_pstatic_ctrl_push_credit with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_fifo_shared_pstatic_ctrl_push_credit_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_config_error;
  logic [0:0] o_push_receiver_in_reset;
  logic [1:0] o_push_credit;
  logic [1:0] o_push_full;
  logic [11:0] o_credit_available_push;
  logic [11:0] o_credit_count_push;
  logic [1:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [1:0] o_pop_empty;
  logic [0:0] o_ram_wr_valid;
  logic [4:0] o_ram_wr_addr;
  logic [31:0] o_ram_wr_data;
  logic [0:0] o_ram_rd_addr_valid;
  logic [4:0] o_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_config_error);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_receiver_in_reset);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_credit);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_full);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_available_push);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_count_push);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_rd_addr);
  end

  br_fifo_shared_pstatic_ctrl_push_credit #(
    .Depth(32),
    .NumFifos(2),
    .RamReadLatency(1),
    .RegisterPopOutputs(1),
    .RegisterPushOutputs(1),
    .StagingBufferDepth(2),
    .Width(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .push_sender_in_reset(rst),
    .push_receiver_in_reset(rst),
    .config_base(lfsr[9:0]),
    .config_bound(lfsr[19:10]),
    .push_credit_stall(lfsr[21:20]),
    .push_valid(lfsr[22]),
    .push_data(lfsr[54:23]),
    .push_fifo_id(lfsr[55]),
    .credit_initial_push({4'd0, lfsr[63:56]}),
    .credit_withhold_push(lfsr[15:4]),
    .pop_ready(lfsr[17:16]),
    .ram_rd_data_valid(lfsr[18]),
    .ram_rd_data(lfsr[50:19]),
    .config_error(o_config_error),
    .push_receiver_in_reset(o_push_receiver_in_reset),
    .push_credit(o_push_credit),
    .push_full(o_push_full),
    .credit_available_push(o_credit_available_push),
    .credit_count_push(o_credit_count_push),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_empty(o_pop_empty),
    .ram_wr_valid(o_ram_wr_valid),
    .ram_wr_addr(o_ram_wr_addr),
    .ram_wr_data(o_ram_wr_data),
    .ram_rd_addr_valid(o_ram_rd_addr_valid),
    .ram_rd_addr(o_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
