// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps icmp with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module icmp_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_eq;
  logic [0:0] o_ne;
  logic [0:0] o_slt;
  logic [0:0] o_sle;
  logic [0:0] o_sgt;
  logic [0:0] o_sge;
  logic [0:0] o_ult;
  logic [0:0] o_ule;
  logic [0:0] o_ugt;
  logic [0:0] o_uge;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_eq);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ne);
      acc = {acc[62:0], acc[63]} ^ 64'(o_slt);
      acc = {acc[62:0], acc[63]} ^ 64'(o_sle);
      acc = {acc[62:0], acc[63]} ^ 64'(o_sgt);
      acc = {acc[62:0], acc[63]} ^ 64'(o_sge);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ult);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ule);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ugt);
      acc = {acc[62:0], acc[63]} ^ 64'(o_uge);
  end

  icmp #(
    .BW(8)
  ) dut (
    .a(lfsr[7:0]),
    .b(lfsr[15:8]),
    .eq(o_eq),
    .ne(o_ne),
    .slt(o_slt),
    .sle(o_sle),
    .sgt(o_sgt),
    .sge(o_sge),
    .ult(o_ult),
    .ule(o_ule),
    .ugt(o_ugt),
    .uge(o_uge)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
