// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axil_write_arbiter with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axil_write_arbiter_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [1:0] o_upstream_awready;
  logic [1:0] o_upstream_wready;
  logic [3:0] o_upstream_bresp;
  logic [1:0] o_upstream_buser;
  logic [1:0] o_upstream_bvalid;
  logic [39:0] o_downstream_awaddr;
  logic [2:0] o_downstream_awprot;
  logic [0:0] o_downstream_awuser;
  logic [0:0] o_downstream_awvalid;
  logic [63:0] o_downstream_wdata;
  logic [7:0] o_downstream_wstrb;
  logic [0:0] o_downstream_wuser;
  logic [0:0] o_downstream_wvalid;
  logic [0:0] o_downstream_bready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_buser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_bready);
  end

  br_amba_axil_write_arbiter dut (
    .clk(clk),
    .rst(rst),
    .upstream_awaddr({16'd0, lfsr[63:0]}),
    .upstream_awprot(lfsr[21:16]),
    .upstream_awuser(lfsr[23:22]),
    .upstream_awvalid(lfsr[25:24]),
    .upstream_wdata({90'd0, lfsr[63:26]}),
    .upstream_wstrb(lfsr[41:26]),
    .upstream_wuser(lfsr[43:42]),
    .upstream_wvalid(lfsr[45:44]),
    .upstream_bready(lfsr[47:46]),
    .downstream_awready(lfsr[48]),
    .downstream_wready(lfsr[49]),
    .downstream_bresp(lfsr[51:50]),
    .downstream_buser(lfsr[52]),
    .downstream_bvalid(lfsr[53]),
    .upstream_awready(o_upstream_awready),
    .upstream_wready(o_upstream_wready),
    .upstream_bresp(o_upstream_bresp),
    .upstream_buser(o_upstream_buser),
    .upstream_bvalid(o_upstream_bvalid),
    .downstream_awaddr(o_downstream_awaddr),
    .downstream_awprot(o_downstream_awprot),
    .downstream_awuser(o_downstream_awuser),
    .downstream_awvalid(o_downstream_awvalid),
    .downstream_wdata(o_downstream_wdata),
    .downstream_wstrb(o_downstream_wstrb),
    .downstream_wuser(o_downstream_wuser),
    .downstream_wvalid(o_downstream_wvalid),
    .downstream_bready(o_downstream_bready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
