// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_csr_demux_select_onehot with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_csr_demux_select_onehot_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_upstream_resp_valid;
  logic [31:0] o_upstream_resp_rdata;
  logic [0:0] o_upstream_resp_decerr;
  logic [0:0] o_upstream_resp_slverr;
  logic [3:0] o_downstream_req_valid;
  logic [3:0] o_downstream_req_write;
  logic [63:0] o_downstream_req_addr;
  logic [127:0] o_downstream_req_wdata;
  logic [15:0] o_downstream_req_wstrb;
  logic [3:0] o_downstream_req_privileged;
  logic [3:0] o_downstream_req_secure;
  logic [3:0] o_downstream_req_abort;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_decerr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_slverr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_write);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_privileged);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_secure);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_abort);
  end

  br_csr_demux_select_onehot #(
    .AddrWidth(16),
    .DataWidth(32),
    .NumDownstreams(4)
  ) dut (
    .clk(clk),
    .rst(rst),
    .select_onehot(lfsr[3:0]),
    .upstream_req_valid(lfsr[4]),
    .upstream_req_write(lfsr[5]),
    .upstream_req_addr(lfsr[21:6]),
    .upstream_req_wdata(lfsr[53:22]),
    .upstream_req_wstrb(lfsr[57:54]),
    .upstream_req_privileged(lfsr[58]),
    .upstream_req_secure(lfsr[59]),
    .upstream_req_abort(lfsr[60]),
    .downstream_resp_valid({1'd0, lfsr[63:61]}),
    .downstream_resp_rdata({65'd0, lfsr[63:1]}),
    .downstream_resp_decerr(lfsr[4:1]),
    .downstream_resp_slverr(lfsr[8:5]),
    .upstream_resp_valid(o_upstream_resp_valid),
    .upstream_resp_rdata(o_upstream_resp_rdata),
    .upstream_resp_decerr(o_upstream_resp_decerr),
    .upstream_resp_slverr(o_upstream_resp_slverr),
    .downstream_req_valid(o_downstream_req_valid),
    .downstream_req_write(o_downstream_req_write),
    .downstream_req_addr(o_downstream_req_addr),
    .downstream_req_wdata(o_downstream_req_wdata),
    .downstream_req_wstrb(o_downstream_req_wstrb),
    .downstream_req_privileged(o_downstream_req_privileged),
    .downstream_req_secure(o_downstream_req_secure),
    .downstream_req_abort(o_downstream_req_abort)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
