// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_flow_serializer with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_flow_serializer_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_push_ready;
  logic [0:0] o_pop_valid;
  logic [7:0] o_pop_data;
  logic [0:0] o_pop_last;
  logic [7:0] o_pop_metadata;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_last);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_metadata);
  end

  br_flow_serializer dut (
    .clk(clk),
    .rst(rst),
    .push_valid(lfsr[0]),
    .push_data({1'd0, lfsr[63:1]}),
    .push_last(lfsr[1]),
    .push_last_dont_care_count(lfsr[4:2]),
    .push_metadata(lfsr[12:5]),
    .pop_ready(lfsr[13]),
    .push_ready(o_push_ready),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_last(o_pop_last),
    .pop_metadata(o_pop_metadata)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
