// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_counter_decr with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_counter_decr_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [7:0] o_value;
  logic [7:0] o_value_next;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_value);
      acc = {acc[62:0], acc[63]} ^ 64'(o_value_next);
  end

  br_counter_decr #(
    .EnableSaturate(0),
    .MaxDecrement(1),
    .MaxValue(255)
  ) dut (
    .clk(clk),
    .rst(rst),
    .reinit(lfsr[0]),
    .initial_value(lfsr[8:1]),
    .decr_valid(lfsr[9]),
    .decr(lfsr[10]),
    .value(o_value),
    .value_next(o_value_next)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
