// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_apb_timing_slice with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_apb_timing_slice_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [31:0] o_prdata_out;
  logic [0:0] o_pready_out;
  logic [0:0] o_pslverr_out;
  logic [31:0] o_paddr_out;
  logic [0:0] o_psel_out;
  logic [0:0] o_penable_out;
  logic [2:0] o_pprot_out;
  logic [3:0] o_pstrb_out;
  logic [0:0] o_pwrite_out;
  logic [31:0] o_pwdata_out;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_prdata_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pready_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pslverr_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_paddr_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_psel_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_penable_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pprot_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pstrb_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pwrite_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pwdata_out);
  end

  br_amba_apb_timing_slice #(
    .AddrWidth(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .paddr_in(lfsr[31:0]),
    .psel_in(lfsr[32]),
    .penable_in(lfsr[33]),
    .pprot_in(lfsr[36:34]),
    .pstrb_in(lfsr[40:37]),
    .pwrite_in(lfsr[41]),
    .pwdata_in({10'd0, lfsr[63:42]}),
    .prdata_in(lfsr[41:10]),
    .pready_in(lfsr[42]),
    .pslverr_in(lfsr[43]),
    .prdata_out(o_prdata_out),
    .pready_out(o_pready_out),
    .pslverr_out(o_pslverr_out),
    .paddr_out(o_paddr_out),
    .psel_out(o_psel_out),
    .penable_out(o_penable_out),
    .pprot_out(o_pprot_out),
    .pstrb_out(o_pstrb_out),
    .pwrite_out(o_pwrite_out),
    .pwdata_out(o_pwdata_out)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
