// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_delay_valid_next_nr with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_delay_valid_next_nr_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_out_valid_next;
  logic [63:0] o_out;
  logic [1:0] o_out_valid_next_stages;
  logic [127:0] o_out_stages;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_valid_next);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_valid_next_stages);
      acc = {acc[62:0], acc[63]} ^ 64'(o_out_stages);
  end

  br_delay_valid_next_nr dut (
    .clk(clk),
    .in_valid_next(lfsr[0]),
    .in({1'd0, lfsr[63:1]}),
    .out_valid_next(o_out_valid_next),
    .out(o_out),
    .out_valid_next_stages(o_out_valid_next_stages),
    .out_stages(o_out_stages)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
