// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_multi_xfer_distributor_rr with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_multi_xfer_distributor_rr_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [2:0] o_push_receivable;
  logic [15:0] o_pop_valid;
  logic [1023:0] o_pop_data;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_receivable);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[63:0]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[127:64]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[191:128]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[255:192]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[319:256]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[383:320]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[447:384]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[511:448]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[575:512]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[639:576]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[703:640]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[767:704]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[831:768]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[895:832]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[959:896]);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data[1023:960]);
  end

  // lfsr rotated by 17*i in word i, so a stimulus window may wrap past bit 63.
  logic [319:0] lfsr_x;
  assign lfsr_x = {{lfsr[59:0], lfsr[63:60]}, {lfsr[12:0], lfsr[63:13]}, {lfsr[29:0], lfsr[63:30]}, {lfsr[46:0], lfsr[63:47]}, lfsr};

  br_multi_xfer_distributor_rr dut (
    .clk(clk),
    .rst(rst),
    .push_sendable(3'd0),
    .push_data(lfsr_x[258:3]),
    .pop_ready(lfsr[18:3]),
    .push_receivable(o_push_receivable),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
