// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_apb_demux with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_apb_demux_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [31:0] o_upstream_prdata;
  logic [0:0] o_upstream_pready;
  logic [0:0] o_upstream_pslverr;
  logic [11:0] o_downstream_paddr;
  logic [0:0] o_downstream_psel;
  logic [0:0] o_downstream_penable;
  logic [2:0] o_downstream_pprot;
  logic [3:0] o_downstream_pstrb;
  logic [0:0] o_downstream_pwrite;
  logic [31:0] o_downstream_pwdata;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_prdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_pready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_pslverr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_paddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_psel);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_penable);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_pprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_pstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_pwrite);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_pwdata);
  end

  br_apb_demux dut (
    .clk(clk),
    .rst(rst),
    .upstream_paddr(lfsr[11:0]),
    .upstream_psel(lfsr[12]),
    .upstream_penable(lfsr[13]),
    .upstream_pprot(lfsr[16:14]),
    .upstream_pstrb(lfsr[20:17]),
    .upstream_pwrite(lfsr[21]),
    .upstream_pwdata(lfsr[53:22]),
    .downstream_addr_base({2'd0, lfsr[63:54]}),
    .downstream_addr_size(lfsr[13:2]),
    .downstream_prdata(lfsr[45:14]),
    .downstream_pready(lfsr[46]),
    .downstream_pslverr(lfsr[47]),
    .upstream_prdata(o_upstream_prdata),
    .upstream_pready(o_upstream_pready),
    .upstream_pslverr(o_upstream_pslverr),
    .downstream_paddr(o_downstream_paddr),
    .downstream_psel(o_downstream_psel),
    .downstream_penable(o_downstream_penable),
    .downstream_pprot(o_downstream_pprot),
    .downstream_pstrb(o_downstream_pstrb),
    .downstream_pwrite(o_downstream_pwrite),
    .downstream_pwdata(o_downstream_pwdata)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
