// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_atb_funnel with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_atb_funnel_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [1:0] o_src_atready;
  logic [0:0] o_dst_atvalid;
  logic [6:0] o_dst_atid;
  logic [31:0] o_dst_atdata;
  logic [1:0] o_dst_atbytes;
  logic [0:0] o_dst_atuser;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_src_atready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dst_atvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dst_atid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dst_atdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dst_atbytes);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dst_atuser);
  end

  br_amba_atb_funnel #(
    .DataWidth(32),
    .NumSources(2),
    .RegisterAtReady(0),
    .UserWidth(1)
  ) dut (
    .clk(clk),
    .rst(rst),
    .src_atvalid(lfsr[1:0]),
    .src_atid(lfsr[15:2]),
    .src_atdata({16'd0, lfsr[63:16]}),
    .src_atbytes(lfsr[19:16]),
    .src_atuser(lfsr[21:20]),
    .dst_atready(lfsr[22]),
    .src_atready(o_src_atready),
    .dst_atvalid(o_dst_atvalid),
    .dst_atid(o_dst_atid),
    .dst_atdata(o_dst_atdata),
    .dst_atbytes(o_dst_atbytes),
    .dst_atuser(o_dst_atuser)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
