// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_fifo_ctrl_1r1w with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_fifo_ctrl_1r1w_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_push_ready;
  logic [0:0] o_pop_valid;
  logic [31:0] o_pop_data;
  logic [0:0] o_full;
  logic [0:0] o_full_next;
  logic [5:0] o_slots;
  logic [5:0] o_slots_next;
  logic [0:0] o_empty;
  logic [0:0] o_empty_next;
  logic [5:0] o_items;
  logic [5:0] o_items_next;
  logic [0:0] o_ram_wr_valid;
  logic [4:0] o_ram_wr_addr;
  logic [31:0] o_ram_wr_data;
  logic [0:0] o_ram_rd_addr_valid;
  logic [4:0] o_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_full);
      acc = {acc[62:0], acc[63]} ^ 64'(o_full_next);
      acc = {acc[62:0], acc[63]} ^ 64'(o_slots);
      acc = {acc[62:0], acc[63]} ^ 64'(o_slots_next);
      acc = {acc[62:0], acc[63]} ^ 64'(o_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_empty_next);
      acc = {acc[62:0], acc[63]} ^ 64'(o_items);
      acc = {acc[62:0], acc[63]} ^ 64'(o_items_next);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ram_rd_addr);
  end

  br_fifo_ctrl_1r1w #(
    .Depth(32),
    .EnableBypass(1),
    .RamReadLatency(1),
    .RegisterPopOutputs(1),
    .Width(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .push_valid(lfsr[0]),
    .push_data(lfsr[32:1]),
    .pop_ready(lfsr[33]),
    .ram_rd_data_valid(lfsr[34]),
    .ram_rd_data({3'd0, lfsr[63:35]}),
    .push_ready(o_push_ready),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .full(o_full),
    .full_next(o_full_next),
    .slots(o_slots),
    .slots_next(o_slots_next),
    .empty(o_empty),
    .empty_next(o_empty_next),
    .items(o_items),
    .items_next(o_items_next),
    .ram_wr_valid(o_ram_wr_valid),
    .ram_wr_addr(o_ram_wr_addr),
    .ram_wr_data(o_ram_wr_data),
    .ram_rd_addr_valid(o_ram_rd_addr_valid),
    .ram_rd_addr(o_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
