# Generated by tools/gen_sdc.py -- do not edit.
# To use real constraints for this test, replace this file; the generator will
# not overwrite a file it did not write (see the marker line above).
# lhdtrack-generated
# Period 10 ns -- expressed in THIS library's time unit, which is
# why constraints are generated per technology (sky130 is 1ns, ASAP7 is 1ps).

create_clock -name clk -period 10.0 [get_ports clk]

# ZERO I/O budget, deliberately. An external delay is part of the arrival
# time OpenSTA reports but NOT of the path delay lhd's OpenTimer reports,
# so any non-zero budget shows up as pure disagreement between the two
# timers. A 20% budget made them look 98% apart on br_delay, whose worst
# path is a zero-logic feedthrough: every nanosecond of the 4.0 ns
# 'critical path' was the budget itself. At zero, both timers measure the
# same thing -- the longest path through the design.
set_input_delay  -clock clk 0.0 [all_inputs -no_clocks]
set_output_delay -clock clk 0.0 [all_outputs]

# No multicycle paths, and no false paths beyond reset above: every other
# path in these blocks is a real one, and an exception added to make a
# number look better is a number that lies.
