// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axi_timing_slice with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axi_timing_slice_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_target_awready;
  logic [0:0] o_target_wready;
  logic [3:0] o_target_bid;
  logic [0:0] o_target_buser;
  logic [1:0] o_target_bresp;
  logic [0:0] o_target_bvalid;
  logic [0:0] o_target_arready;
  logic [3:0] o_target_rid;
  logic [31:0] o_target_rdata;
  logic [0:0] o_target_ruser;
  logic [1:0] o_target_rresp;
  logic [0:0] o_target_rlast;
  logic [0:0] o_target_rvalid;
  logic [31:0] o_init_awaddr;
  logic [3:0] o_init_awid;
  logic [7:0] o_init_awlen;
  logic [2:0] o_init_awsize;
  logic [1:0] o_init_awburst;
  logic [2:0] o_init_awprot;
  logic [0:0] o_init_awuser;
  logic [0:0] o_init_awvalid;
  logic [31:0] o_init_wdata;
  logic [3:0] o_init_wstrb;
  logic [0:0] o_init_wuser;
  logic [0:0] o_init_wlast;
  logic [0:0] o_init_wvalid;
  logic [0:0] o_init_bready;
  logic [31:0] o_init_araddr;
  logic [3:0] o_init_arid;
  logic [7:0] o_init_arlen;
  logic [2:0] o_init_arsize;
  logic [1:0] o_init_arburst;
  logic [2:0] o_init_arprot;
  logic [0:0] o_init_aruser;
  logic [0:0] o_init_arvalid;
  logic [0:0] o_init_rready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_bid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_buser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_ruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rlast);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awlen);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awsize);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awburst);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wlast);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_bready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_araddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arlen);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arsize);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arburst);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_aruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_rready);
  end

  br_amba_axi_timing_slice dut (
    .clk(clk),
    .rst(rst),
    .target_awaddr(lfsr[31:0]),
    .target_awid(lfsr[35:32]),
    .target_awlen(lfsr[43:36]),
    .target_awsize(lfsr[46:44]),
    .target_awburst(lfsr[48:47]),
    .target_awprot(lfsr[51:49]),
    .target_awuser(lfsr[52]),
    .target_awvalid(lfsr[53]),
    .target_wdata({22'd0, lfsr[63:54]}),
    .target_wstrb(lfsr[25:22]),
    .target_wuser(lfsr[26]),
    .target_wlast(lfsr[27]),
    .target_wvalid(lfsr[28]),
    .target_bready(lfsr[29]),
    .target_araddr(lfsr[61:30]),
    .target_arid({2'd0, lfsr[63:62]}),
    .target_arlen(lfsr[9:2]),
    .target_arsize(lfsr[12:10]),
    .target_arburst(lfsr[14:13]),
    .target_arprot(lfsr[17:15]),
    .target_aruser(lfsr[18]),
    .target_arvalid(lfsr[19]),
    .target_rready(lfsr[20]),
    .init_awready(lfsr[21]),
    .init_wready(lfsr[22]),
    .init_bid(lfsr[26:23]),
    .init_buser(lfsr[27]),
    .init_bresp(lfsr[29:28]),
    .init_bvalid(lfsr[30]),
    .init_arready(lfsr[31]),
    .init_rid(lfsr[35:32]),
    .init_rdata({4'd0, lfsr[63:36]}),
    .init_ruser(lfsr[4]),
    .init_rresp(lfsr[6:5]),
    .init_rlast(lfsr[7]),
    .init_rvalid(lfsr[8]),
    .target_awready(o_target_awready),
    .target_wready(o_target_wready),
    .target_bid(o_target_bid),
    .target_buser(o_target_buser),
    .target_bresp(o_target_bresp),
    .target_bvalid(o_target_bvalid),
    .target_arready(o_target_arready),
    .target_rid(o_target_rid),
    .target_rdata(o_target_rdata),
    .target_ruser(o_target_ruser),
    .target_rresp(o_target_rresp),
    .target_rlast(o_target_rlast),
    .target_rvalid(o_target_rvalid),
    .init_awaddr(o_init_awaddr),
    .init_awid(o_init_awid),
    .init_awlen(o_init_awlen),
    .init_awsize(o_init_awsize),
    .init_awburst(o_init_awburst),
    .init_awprot(o_init_awprot),
    .init_awuser(o_init_awuser),
    .init_awvalid(o_init_awvalid),
    .init_wdata(o_init_wdata),
    .init_wstrb(o_init_wstrb),
    .init_wuser(o_init_wuser),
    .init_wlast(o_init_wlast),
    .init_wvalid(o_init_wvalid),
    .init_bready(o_init_bready),
    .init_araddr(o_init_araddr),
    .init_arid(o_init_arid),
    .init_arlen(o_init_arlen),
    .init_arsize(o_init_arsize),
    .init_arburst(o_init_arburst),
    .init_arprot(o_init_arprot),
    .init_aruser(o_init_aruser),
    .init_arvalid(o_init_arvalid),
    .init_rready(o_init_rready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
