// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_credit_sender_vc with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_credit_sender_vc_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [3:0] o_request;
  logic [0:0] o_enable_priority_update;
  logic [3:0] o_push_ready;
  logic [0:0] o_pop_sender_in_reset;
  logic [0:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [1:0] o_pop_vc;
  logic [19:0] o_credit_count;
  logic [19:0] o_credit_available;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_request);
      acc = {acc[62:0], acc[63]} ^ 64'(o_enable_priority_update);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_sender_in_reset);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_vc);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_count);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_available);
  end

  br_credit_sender_vc dut (
    .clk(clk),
    .rst(rst),
    .pop_sender_in_reset(rst),
    .pop_receiver_in_reset(rst),
    .can_grant(lfsr[3:0]),
    .grant(lfsr[7:4]),
    .push_valid(lfsr[11:8]),
    .push_data({204'd0, lfsr[63:12]}),
    .pop_credit(lfsr[23:12]),
    .credit_initial(lfsr[43:24]),
    .credit_withhold(lfsr[63:44]),
    .request(o_request),
    .enable_priority_update(o_enable_priority_update),
    .push_ready(o_push_ready),
    .pop_sender_in_reset(o_pop_sender_in_reset),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_vc(o_pop_vc),
    .credit_count(o_credit_count),
    .credit_available(o_credit_available)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
