// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_fifo_shared_dynamic_ctrl_push_credit_pop_credit with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_fifo_shared_dynamic_ctrl_push_credit_pop_credit_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_push_receiver_in_reset;
  logic [1:0] o_push_credit;
  logic [0:0] o_push_full;
  logic [5:0] o_credit_available_push;
  logic [5:0] o_credit_count_push;
  logic [0:0] o_pop_sender_in_reset;
  logic [1:0] o_pop_valid;
  logic [1:0] o_pop_fifo_id;
  logic [63:0] o_pop_data;
  logic [1:0] o_pop_empty;
  logic [5:0] o_credit_available_pop;
  logic [5:0] o_credit_count_pop;
  logic [1:0] o_data_ram_wr_valid;
  logic [9:0] o_data_ram_wr_addr;
  logic [63:0] o_data_ram_wr_data;
  logic [1:0] o_data_ram_rd_addr_valid;
  logic [9:0] o_data_ram_rd_addr;
  logic [1:0] o_ptr_ram_wr_valid;
  logic [9:0] o_ptr_ram_wr_addr;
  logic [9:0] o_ptr_ram_wr_data;
  logic [1:0] o_ptr_ram_rd_addr_valid;
  logic [9:0] o_ptr_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_receiver_in_reset);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_credit);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_full);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_available_push);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_count_push);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_sender_in_reset);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_fifo_id);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_available_pop);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_count_pop);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_rd_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_rd_addr);
  end

  br_fifo_shared_dynamic_ctrl_push_credit_pop_credit dut (
    .clk(clk),
    .rst(rst),
    .push_sender_in_reset(rst),
    .push_receiver_in_reset(rst),
    .pop_sender_in_reset(rst),
    .pop_receiver_in_reset(rst),
    .push_credit_stall(lfsr[0]),
    .push_valid(lfsr[2:1]),
    .push_data({3'd0, lfsr[63:3]}),
    .push_fifo_id(lfsr[4:3]),
    .credit_initial_push(lfsr[10:5]),
    .credit_withhold_push(lfsr[16:11]),
    .pop_credit(lfsr[18:17]),
    .credit_initial_pop(lfsr[24:19]),
    .credit_withhold_pop(lfsr[30:25]),
    .data_ram_rd_data_valid(lfsr[32:31]),
    .data_ram_rd_data({33'd0, lfsr[63:33]}),
    .ptr_ram_rd_data_valid(lfsr[34:33]),
    .ptr_ram_rd_data(lfsr[44:35]),
    .push_receiver_in_reset(o_push_receiver_in_reset),
    .push_credit(o_push_credit),
    .push_full(o_push_full),
    .credit_available_push(o_credit_available_push),
    .credit_count_push(o_credit_count_push),
    .pop_sender_in_reset(o_pop_sender_in_reset),
    .pop_valid(o_pop_valid),
    .pop_fifo_id(o_pop_fifo_id),
    .pop_data(o_pop_data),
    .pop_empty(o_pop_empty),
    .credit_available_pop(o_credit_available_pop),
    .credit_count_pop(o_credit_count_pop),
    .data_ram_wr_valid(o_data_ram_wr_valid),
    .data_ram_wr_addr(o_data_ram_wr_addr),
    .data_ram_wr_data(o_data_ram_wr_data),
    .data_ram_rd_addr_valid(o_data_ram_rd_addr_valid),
    .data_ram_rd_addr(o_data_ram_rd_addr),
    .ptr_ram_wr_valid(o_ptr_ram_wr_valid),
    .ptr_ram_wr_addr(o_ptr_ram_wr_addr),
    .ptr_ram_wr_data(o_ptr_ram_wr_data),
    .ptr_ram_rd_addr_valid(o_ptr_ram_rd_addr_valid),
    .ptr_ram_rd_addr(o_ptr_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
