// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axi_demux with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axi_demux_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_upstream_awready;
  logic [0:0] o_upstream_wready;
  logic [0:0] o_upstream_bid;
  logic [0:0] o_upstream_buser;
  logic [1:0] o_upstream_bresp;
  logic [0:0] o_upstream_bvalid;
  logic [0:0] o_upstream_arready;
  logic [0:0] o_upstream_rid;
  logic [31:0] o_upstream_rdata;
  logic [0:0] o_upstream_ruser;
  logic [1:0] o_upstream_rresp;
  logic [0:0] o_upstream_rlast;
  logic [0:0] o_upstream_rvalid;
  logic [63:0] o_downstream_awaddr;
  logic [1:0] o_downstream_awid;
  logic [15:0] o_downstream_awlen;
  logic [5:0] o_downstream_awsize;
  logic [3:0] o_downstream_awburst;
  logic [7:0] o_downstream_awcache;
  logic [5:0] o_downstream_awprot;
  logic [1:0] o_downstream_awuser;
  logic [1:0] o_downstream_awvalid;
  logic [63:0] o_downstream_wdata;
  logic [7:0] o_downstream_wstrb;
  logic [1:0] o_downstream_wuser;
  logic [1:0] o_downstream_wlast;
  logic [1:0] o_downstream_wvalid;
  logic [1:0] o_downstream_bready;
  logic [63:0] o_downstream_araddr;
  logic [1:0] o_downstream_arid;
  logic [15:0] o_downstream_arlen;
  logic [5:0] o_downstream_arsize;
  logic [3:0] o_downstream_arburst;
  logic [7:0] o_downstream_arcache;
  logic [5:0] o_downstream_arprot;
  logic [1:0] o_downstream_aruser;
  logic [1:0] o_downstream_arvalid;
  logic [1:0] o_downstream_rready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_bid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_buser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_rid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_ruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_rlast);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awlen);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awsize);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awburst);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awcache);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wlast);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_bready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_araddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_arid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_arlen);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_arsize);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_arburst);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_arcache);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_arprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_aruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_arvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_rready);
  end

  br_amba_axi_demux dut (
    .clk(clk),
    .rst(rst),
    .upstream_aw_sub_select(lfsr[0]),
    .upstream_awaddr(lfsr[32:1]),
    .upstream_awid(lfsr[33]),
    .upstream_awlen(lfsr[41:34]),
    .upstream_awsize(lfsr[44:42]),
    .upstream_awburst(lfsr[46:45]),
    .upstream_awcache(lfsr[50:47]),
    .upstream_awprot(lfsr[53:51]),
    .upstream_awuser(lfsr[54]),
    .upstream_awvalid(lfsr[55]),
    .upstream_wdata({24'd0, lfsr[63:56]}),
    .upstream_wstrb(lfsr[27:24]),
    .upstream_wuser(lfsr[28]),
    .upstream_wlast(lfsr[29]),
    .upstream_wvalid(lfsr[30]),
    .upstream_bready(lfsr[31]),
    .upstream_ar_sub_select(lfsr[32]),
    .upstream_araddr({1'd0, lfsr[63:33]}),
    .upstream_arid(lfsr[1]),
    .upstream_arlen(lfsr[9:2]),
    .upstream_arsize(lfsr[12:10]),
    .upstream_arburst(lfsr[14:13]),
    .upstream_arcache(lfsr[18:15]),
    .upstream_arprot(lfsr[21:19]),
    .upstream_aruser(lfsr[22]),
    .upstream_arvalid(lfsr[23]),
    .upstream_rready(lfsr[24]),
    .downstream_awready(lfsr[26:25]),
    .downstream_wready(lfsr[28:27]),
    .downstream_bid(lfsr[30:29]),
    .downstream_buser(lfsr[32:31]),
    .downstream_bresp(lfsr[36:33]),
    .downstream_bvalid(lfsr[38:37]),
    .downstream_arready(lfsr[40:39]),
    .downstream_rid(lfsr[42:41]),
    .downstream_rdata({43'd0, lfsr[63:43]}),
    .downstream_ruser(lfsr[44:43]),
    .downstream_rresp(lfsr[48:45]),
    .downstream_rlast(lfsr[50:49]),
    .downstream_rvalid(lfsr[52:51]),
    .upstream_awready(o_upstream_awready),
    .upstream_wready(o_upstream_wready),
    .upstream_bid(o_upstream_bid),
    .upstream_buser(o_upstream_buser),
    .upstream_bresp(o_upstream_bresp),
    .upstream_bvalid(o_upstream_bvalid),
    .upstream_arready(o_upstream_arready),
    .upstream_rid(o_upstream_rid),
    .upstream_rdata(o_upstream_rdata),
    .upstream_ruser(o_upstream_ruser),
    .upstream_rresp(o_upstream_rresp),
    .upstream_rlast(o_upstream_rlast),
    .upstream_rvalid(o_upstream_rvalid),
    .downstream_awaddr(o_downstream_awaddr),
    .downstream_awid(o_downstream_awid),
    .downstream_awlen(o_downstream_awlen),
    .downstream_awsize(o_downstream_awsize),
    .downstream_awburst(o_downstream_awburst),
    .downstream_awcache(o_downstream_awcache),
    .downstream_awprot(o_downstream_awprot),
    .downstream_awuser(o_downstream_awuser),
    .downstream_awvalid(o_downstream_awvalid),
    .downstream_wdata(o_downstream_wdata),
    .downstream_wstrb(o_downstream_wstrb),
    .downstream_wuser(o_downstream_wuser),
    .downstream_wlast(o_downstream_wlast),
    .downstream_wvalid(o_downstream_wvalid),
    .downstream_bready(o_downstream_bready),
    .downstream_araddr(o_downstream_araddr),
    .downstream_arid(o_downstream_arid),
    .downstream_arlen(o_downstream_arlen),
    .downstream_arsize(o_downstream_arsize),
    .downstream_arburst(o_downstream_arburst),
    .downstream_arcache(o_downstream_arcache),
    .downstream_arprot(o_downstream_arprot),
    .downstream_aruser(o_downstream_aruser),
    .downstream_arvalid(o_downstream_arvalid),
    .downstream_rready(o_downstream_rready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
