// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_csr_mem_interface with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_csr_mem_interface_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_resp_valid;
  logic [31:0] o_resp_rdata;
  logic [0:0] o_resp_slverr;
  logic [0:0] o_resp_decerr;
  logic [0:0] o_mem_access_valid;
  logic [3:0] o_mem_access_addr;
  logic [0:0] o_mem_access_wr_en;
  logic [31:0] o_mem_access_wr_data;
  logic [3:0] o_mem_access_wr_strb;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_resp_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_resp_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_resp_slverr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_resp_decerr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_mem_access_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_mem_access_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_mem_access_wr_en);
      acc = {acc[62:0], acc[63]} ^ 64'(o_mem_access_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_mem_access_wr_strb);
  end

  br_csr_mem_interface dut (
    .clk(clk),
    .rst(rst),
    .req_valid(lfsr[0]),
    .req_write(lfsr[1]),
    .req_addr(lfsr[17:2]),
    .req_wdata(lfsr[49:18]),
    .req_wstrb(lfsr[53:50]),
    .req_privileged(lfsr[54]),
    .req_secure(lfsr[55]),
    .req_abort(lfsr[56]),
    .mem_access_ready(lfsr[57]),
    .mem_read_data_valid(lfsr[58]),
    .mem_read_data({27'd0, lfsr[63:59]}),
    .mem_read_data_err(lfsr[27]),
    .resp_valid(o_resp_valid),
    .resp_rdata(o_resp_rdata),
    .resp_slverr(o_resp_slverr),
    .resp_decerr(o_resp_decerr),
    .mem_access_valid(o_mem_access_valid),
    .mem_access_addr(o_mem_access_addr),
    .mem_access_wr_en(o_mem_access_wr_en),
    .mem_access_wr_data(o_mem_access_wr_data),
    .mem_access_wr_strb(o_mem_access_wr_strb)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
