package(default_visibility = ["//visibility:public"])

genrule(
    name = "merged_liberty",
    srcs = [
        "@asap7_ao//file",
        "@asap7_invbuf//file",
        "@asap7_oa//file",
        "@asap7_seq//file",
        "@asap7_simple//file",
    ],
    outs = ["asap7sc7p5t_RVT_TT_merged.lib"],
    cmd = "$(execpath //:merge_liberty) --output $@ " +
          "$(location @asap7_ao//file) " +
          "$(location @asap7_invbuf//file) " +
          "$(location @asap7_oa//file) " +
          "$(location @asap7_simple//file) " +
          "$(location @asap7_seq//file)",
    tools = ["//:merge_liberty"],
)

filegroup(
    name = "liberty",
    srcs = [":merged_liberty"],
)

exports_files(["VERSION"])
