// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axil2apb with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axil2apb_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_awready;
  logic [0:0] o_wready;
  logic [1:0] o_bresp;
  logic [0:0] o_bvalid;
  logic [0:0] o_arready;
  logic [31:0] o_rdata;
  logic [1:0] o_rresp;
  logic [0:0] o_rvalid;
  logic [31:0] o_paddr;
  logic [0:0] o_psel;
  logic [0:0] o_penable;
  logic [2:0] o_pprot;
  logic [3:0] o_pstrb;
  logic [0:0] o_pwrite;
  logic [31:0] o_pwdata;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_paddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_psel);
      acc = {acc[62:0], acc[63]} ^ 64'(o_penable);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pwrite);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pwdata);
  end

  br_amba_axil2apb dut (
    .clk(clk),
    .rst(rst),
    .awaddr(lfsr[31:0]),
    .awprot(lfsr[34:32]),
    .awvalid(lfsr[35]),
    .wdata({4'd0, lfsr[63:36]}),
    .wstrb(lfsr[7:4]),
    .wvalid(lfsr[8]),
    .bready(lfsr[9]),
    .araddr(lfsr[41:10]),
    .arprot(lfsr[44:42]),
    .arvalid(lfsr[45]),
    .rready(lfsr[46]),
    .prdata({15'd0, lfsr[63:47]}),
    .pready(lfsr[15]),
    .pslverr(lfsr[16]),
    .awready(o_awready),
    .wready(o_wready),
    .bresp(o_bresp),
    .bvalid(o_bvalid),
    .arready(o_arready),
    .rdata(o_rdata),
    .rresp(o_rresp),
    .rvalid(o_rvalid),
    .paddr(o_paddr),
    .psel(o_psel),
    .penable(o_penable),
    .pprot(o_pprot),
    .pstrb(o_pstrb),
    .pwrite(o_pwrite),
    .pwdata(o_pwdata)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
