// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_csr_cdc with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_csr_cdc_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_upstream_resp_valid;
  logic [31:0] o_upstream_resp_rdata;
  logic [0:0] o_upstream_resp_slverr;
  logic [0:0] o_upstream_resp_decerr;
  logic [0:0] o_downstream_req_valid;
  logic [0:0] o_downstream_req_write;
  logic [15:0] o_downstream_req_addr;
  logic [31:0] o_downstream_req_wdata;
  logic [3:0] o_downstream_req_wstrb;
  logic [0:0] o_downstream_req_secure;
  logic [0:0] o_downstream_req_privileged;
  logic [0:0] o_downstream_req_abort;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_slverr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_upstream_resp_decerr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_write);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_secure);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_privileged);
      acc = {acc[62:0], acc[63]} ^ 64'(o_downstream_req_abort);
  end

  br_csr_cdc dut (
    .upstream_clk(clk),
    .downstream_clk(clk),
    .upstream_rst(rst),
    .downstream_rst(rst),
    .upstream_req_valid(lfsr[0]),
    .upstream_req_write(lfsr[1]),
    .upstream_req_addr(lfsr[17:2]),
    .upstream_req_wdata(lfsr[49:18]),
    .upstream_req_wstrb(lfsr[53:50]),
    .upstream_req_secure(lfsr[54]),
    .upstream_req_privileged(lfsr[55]),
    .upstream_req_abort(lfsr[56]),
    .downstream_resp_valid(lfsr[57]),
    .downstream_resp_rdata({26'd0, lfsr[63:58]}),
    .downstream_resp_slverr(lfsr[26]),
    .downstream_resp_decerr(lfsr[27]),
    .upstream_resp_valid(o_upstream_resp_valid),
    .upstream_resp_rdata(o_upstream_resp_rdata),
    .upstream_resp_slverr(o_upstream_resp_slverr),
    .upstream_resp_decerr(o_upstream_resp_decerr),
    .downstream_req_valid(o_downstream_req_valid),
    .downstream_req_write(o_downstream_req_write),
    .downstream_req_addr(o_downstream_req_addr),
    .downstream_req_wdata(o_downstream_req_wdata),
    .downstream_req_wstrb(o_downstream_req_wstrb),
    .downstream_req_secure(o_downstream_req_secure),
    .downstream_req_privileged(o_downstream_req_privileged),
    .downstream_req_abort(o_downstream_req_abort)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
