// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_ecc_sed_decoder with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_ecc_sed_decoder_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_dec_valid;
  logic [32:0] o_dec_codeword;
  logic [0:0] o_dec_error_due;
  logic [0:0] o_dec_error_syndrome;
  logic [31:0] o_dec_data;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_dec_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dec_codeword);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dec_error_due);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dec_error_syndrome);
      acc = {acc[62:0], acc[63]} ^ 64'(o_dec_data);
  end

  br_ecc_sed_decoder dut (
    .clk(clk),
    .rst(rst),
    .rcv_valid(lfsr[0]),
    .rcv_codeword(lfsr[33:1]),
    .dec_valid(o_dec_valid),
    .dec_codeword(o_dec_codeword),
    .dec_error_due(o_dec_error_due),
    .dec_error_syndrome(o_dec_error_syndrome),
    .dec_data(o_dec_data)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
