// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_fifo_shared_dynamic_ctrl_ext_arbiter with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_fifo_shared_dynamic_ctrl_ext_arbiter_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [1:0] o_push_ready;
  logic [0:0] o_push_full;
  logic [1:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [1:0] o_pop_empty;
  logic [3:0] o_arb_request;
  logic [1:0] o_arb_enable_priority_update;
  logic [1:0] o_data_ram_wr_valid;
  logic [9:0] o_data_ram_wr_addr;
  logic [63:0] o_data_ram_wr_data;
  logic [1:0] o_data_ram_rd_addr_valid;
  logic [9:0] o_data_ram_rd_addr;
  logic [1:0] o_ptr_ram_wr_valid;
  logic [9:0] o_ptr_ram_wr_addr;
  logic [9:0] o_ptr_ram_wr_data;
  logic [1:0] o_ptr_ram_rd_addr_valid;
  logic [9:0] o_ptr_ram_rd_addr;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_full);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_arb_request);
      acc = {acc[62:0], acc[63]} ^ 64'(o_arb_enable_priority_update);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_data_ram_rd_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_addr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_wr_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_rd_addr_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_ptr_ram_rd_addr);
  end

  br_fifo_shared_dynamic_ctrl_ext_arbiter #(
    .DataRamReadLatency(1),
    .Depth(32),
    .NumFifos(2),
    .NumReadPorts(2),
    .NumWritePorts(2),
    .PointerRamReadLatency(1),
    .RegisterDeallocation(1),
    .RegisterPopOutputs(1),
    .StagingBufferDepth(2),
    .Width(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .push_valid(lfsr[1:0]),
    .push_data({2'd0, lfsr[63:2]}),
    .push_fifo_id(lfsr[3:2]),
    .pop_ready(lfsr[5:4]),
    .arb_grant(lfsr[9:6]),
    .data_ram_rd_data_valid(lfsr[11:10]),
    .data_ram_rd_data({12'd0, lfsr[63:12]}),
    .ptr_ram_rd_data_valid(lfsr[13:12]),
    .ptr_ram_rd_data(lfsr[23:14]),
    .push_ready(o_push_ready),
    .push_full(o_push_full),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_empty(o_pop_empty),
    .arb_request(o_arb_request),
    .arb_enable_priority_update(o_arb_enable_priority_update),
    .data_ram_wr_valid(o_data_ram_wr_valid),
    .data_ram_wr_addr(o_data_ram_wr_addr),
    .data_ram_wr_data(o_data_ram_wr_data),
    .data_ram_rd_addr_valid(o_data_ram_rd_addr_valid),
    .data_ram_rd_addr(o_data_ram_rd_addr),
    .ptr_ram_wr_valid(o_ptr_ram_wr_valid),
    .ptr_ram_wr_addr(o_ptr_ram_wr_addr),
    .ptr_ram_wr_data(o_ptr_ram_wr_data),
    .ptr_ram_rd_addr_valid(o_ptr_ram_rd_addr_valid),
    .ptr_ram_rd_addr(o_ptr_ram_rd_addr)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
