// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps comparator with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module comparator_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_eq;
  logic [0:0] o_lt;
  logic [0:0] o_gt;
  logic [0:0] o_lte;
  logic [0:0] o_gte;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_eq);
      acc = {acc[62:0], acc[63]} ^ 64'(o_lt);
      acc = {acc[62:0], acc[63]} ^ 64'(o_gt);
      acc = {acc[62:0], acc[63]} ^ 64'(o_lte);
      acc = {acc[62:0], acc[63]} ^ 64'(o_gte);
  end

  comparator dut (
    .a(lfsr[7:0]),
    .b(lfsr[15:8]),
    .eq(o_eq),
    .lt(o_lt),
    .gt(o_gt),
    .lte(o_lte),
    .gte(o_gte)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
