"""Generate the four simulation files of a test, from one port list.

    sim/<top>_harness.sv     RTL harness: LFSR stimulus + checksum, wraps the SV DUT
    sim/<top>_harness.prp    the same harness in Pyrope, wrapping the Pyrope DUT
    sim/<top>_tb.prp         `lhd sim` driver: tick N, read checksum, print
    sim/<top>_tb_verilator.cpp   the C++ twin of that driver

WHY THE STIMULUS LIVES IN RTL. The obvious design puts the LFSR in the
testbench and drives ports from software. That makes the three simulators do
*different* work -- verilator's C++ harness against `lhd sim`'s generated
driver -- and it forces the generator to know each port's exact type in each
language, which is where a generated testbench actually breaks.

Putting the stimulus and the checksum inside the harness RTL instead means both
tools COMPILE AND SIMULATE THE SAME STATE MACHINE, and the driver shrinks to
"tick N times, read one 64-bit output". The interface between driver and design
is then a single unsigned integer, which cannot be mistyped.

The cost is dilution: on a very small DUT the harness is a measurable share of
the simulated work, so absolute cycles/s understates the tool. Ratios between
the three simulators stay valid, which is what the tracker reports.

WHY THE CHECKSUM AVOIDS MULTIPLY. A rotate-and-xor fold costs a few gates; a
64x64 multiply would dwarf most blocks in this corpus and turn every row into a
multiplier benchmark.

A GENERATED HARNESS IS A STARTING POINT. The Pyrope half in particular assumes
the DUT is a `mod` with named ports; a hand-written idiomatic Pyrope module may
present a different interface, and adjusting the harness is part of promoting a
test to `status.pyrope = "idiomatic"`.
"""

from __future__ import annotations

from pathlib import Path

from ports import CLOCK_RE, RESET_RE, Port, PortList

MARKER = "lhdtrack-generated"
SEED = 2611923443488327891  # 0x243F6A8885A308D3 -- the fractional bits of pi
RESET_CYCLES = 4

_HEAD_SV = f"// Generated by tools/gen_testbench.py -- {MARKER}. Simulation only.\n"
_HEAD_PRP = f"// Generated by tools/gen_testbench.py -- {MARKER}. Simulation only.\n"


# Pyrope keywords and operators. A port named `in`, `out` is fine but `in` is
# the membership operator, so any identifier landing in this set must be
# backtick-escaped -- Pyrope's documented escape for exactly this case.
_PRP_KEYWORDS = {
    "and", "assert", "assume", "break", "case", "comb", "comptime", "const",
    "continue", "does", "elif", "else", "enum", "equals", "false", "fluid",
    "for", "formal", "has", "if", "implies", "import", "in", "is", "loop",
    "match", "mod", "mut", "nil", "not", "or", "past", "pipe", "pub", "ref",
    "reg", "return", "sat", "self", "stage", "step", "test", "tick", "true",
    "type", "while", "wire", "wrap",
}


# Names the generated harness declares itself; a destructured DUT output that
# collides with one of these would shadow it.
_HARNESS_LOCALS = frozenset(
    {"dut", "clk", "rst", "checksum", "lfsr", "lfsr_x", "sum", "nxt", "acc", "r"}
)


def pid(name: str) -> str:
    """A port name, safe to use as a Pyrope identifier."""
    return f"`{name}`" if name in _PRP_KEYWORDS else name


def is_generated(path: Path) -> bool:
    return path.exists() and MARKER in path.read_text(errors="replace")


# --------------------------------------------------------------- slicing ----
def _slices(inputs: list[Port]) -> list[tuple[Port, int, int]]:
    """Assign each stimulus input a window of the 64-bit LFSR, as (port, lo, hi).

    Consecutive windows, so inputs within the first 64 bits never receive
    correlated bits, and wrapped modulo 64 so a design with more than 64 bits
    of input still gets every port driven.

    A window may run PAST bit 63: it then reads `lfsr_x` (see _lfsr_x_copies).
    It used to be clipped at 63 and zero-padded, which pinned the top bits of
    every wide or late-starting input at zero for the whole run -- half the
    corpus simulated with part of its input space never toggling.
    """
    out, bit = [], 0
    for p in inputs:
        width = max(1, p.width)
        lo = bit % 64
        out.append((p, lo, lo + width - 1))
        bit += width
    return out


def _lfsr_x_copies(stim: list[tuple[Port, int, int]], constants: dict[str, int]) -> int:
    """How many 64-bit words `lfsr_x` needs for the widest window; 0 if none wraps.

    Word i of `lfsr_x` is `lfsr` rotated left by ROT*i, NOT a plain copy: an
    array input (`in[8][64]`) lands one element per word, and plain copies
    would give every element the same value -- a mux selecting between equal
    inputs checks nothing. ROT is odd, so the first 64 rotations are distinct.
    """
    top = max((hi for p, _, hi in stim if p.name not in constants), default=0)
    return 0 if top < 64 else top // 64 + 1


ROT = 17


def _rot(i: int) -> int:
    return (ROT * i) % 64


def _lfsr_x_sv(copies: int) -> str:
    words = []
    for i in reversed(range(copies)):
        r = _rot(i)
        words.append("lfsr" if r == 0 else f"{{lfsr[{63 - r}:0], lfsr[63:{64 - r}]}}")
    return (
        f"\n  // lfsr rotated by {ROT}*i in word i, so a stimulus window may wrap past bit 63.\n"
        f"  logic [{64 * copies - 1}:0] lfsr_x;\n"
        f"  assign lfsr_x = {{{', '.join(words)}}};\n"
    )


def _lfsr_x_prp(copies: int) -> str:
    terms = []
    for i in range(copies):
        r = _rot(i)
        word = "lfsr" if r == 0 else f"((lfsr#[0..={63 - r}] << {r}) | lfsr#[{64 - r}..=63])"
        terms.append(word if i == 0 else f"({word} << {64 * i})")
    body = " |\n    ".join(terms)
    return (
        f"\n  // lfsr rotated by {ROT}*i in word i, so a stimulus window may wrap past bit 63.\n"
        f"  const lfsr_x:U{64 * copies} = {body}\n"
    )


def _chunks(width: int) -> list[tuple[int, int]]:
    """64-bit (lo, hi) chunks of an output, so every bit reaches the checksum."""
    width = max(1, width)
    return [(lo, min(lo + 63, width - 1)) for lo in range(0, width, 64)]


def _input_constants(pl: PortList, values: dict[str, int] | None) -> dict[str, int]:
    """Validate test-specific constants used to keep generated stimulus legal."""
    constants = values or {}
    inputs = {p.name: p for p in pl.inputs}
    unknown = set(constants) - set(inputs)
    if unknown:
        raise HarnessError(f"{pl.top}: simulation constants name non-input ports {sorted(unknown)}")
    for name, value in constants.items():
        if not isinstance(value, int):
            raise HarnessError(f"{pl.top}: simulation constant {name} must be an integer")
        width = max(1, inputs[name].width)
        if value < 0 or value >= 1 << width:
            raise HarnessError(
                f"{pl.top}: simulation constant {name}={value} does not fit u{width}"
            )
    return constants


# ---------------------------------------------------------- SV harness ------
class HarnessError(RuntimeError):
    """The generated harness would not faithfully exercise the DUT."""


def _check_connections(pl: PortList, connected: list[str]) -> None:
    """Every DUT port is wired exactly once, and no clock is driven by data.

    THE CHECKSUM ORACLE CANNOT CATCH A BAD HARNESS. All three simulators share
    it, so if the harness clocks a design from a random LFSR bit -- which this
    generator did until the clock pattern was widened to catch `wr_clk` -- all
    three agree on the same nonsense and the oracle reports nothing. Twice now
    a harness bug has hidden behind that agreement, so the harness checks
    itself instead of relying on a downstream comparison that structurally
    cannot see it.
    """
    want = {p.name for p in pl.ports}
    got = list(connected)
    missing = want - set(got)
    if missing:
        raise HarnessError(
            f"{pl.top}: harness leaves {sorted(missing)} unconnected -- an undriven "
            "clock or reset simulates against a floating signal"
        )
    dupes = {n for n in got if got.count(n) > 1}
    if dupes:
        raise HarnessError(f"{pl.top}: harness wires {sorted(dupes)} more than once")
    stim = {p.name for p in pl.inputs}
    misdriven = {n for n in stim if CLOCK_RE.match(n) or RESET_RE.match(n)}
    if misdriven:
        raise HarnessError(
            f"{pl.top}: {sorted(misdriven)} would be driven by the stimulus LFSR "
            "but is named like a clock or reset"
        )


def harness_sv(
    pl: PortList, params: dict, input_constants: dict[str, int] | None = None
) -> str:
    top = pl.top
    stim = _slices(pl.inputs)
    outs = pl.outputs
    constants = _input_constants(pl, input_constants)

    decls = [f"  logic [{max(1, p.width)-1}:0] o_{p.name};" for p in outs]

    conns = []
    # EVERY clock and reset port, not just the first. A multi-domain block
    # declares several (`wr_clk`/`rd_clk`), and connecting only one leaves the
    # others floating -- which either fails elaboration or, worse, simulates
    # against an undriven clock.
    #
    # They are all tied to the SAME clk/rst, which makes a multi-domain design
    # synchronous for this benchmark. That is a real simplification: a CDC block
    # wired this way does not exercise its crossing. It is the right default
    # here -- the harness measures synthesis and simulation throughput, not
    # protocol behaviour -- but a CDC test that wants its crossing exercised
    # needs a hand-written harness.
    for c in pl.clocks:
        conns.append(f"    .{c.name}(clk)")
    for r in pl.resets:
        conns.append(f"    .{r.name}({'~rst' if r.active_low_reset else 'rst'})")
    copies = _lfsr_x_copies(stim, constants)
    for p, lo, hi in stim:
        width = max(1, p.width)
        if p.name in constants:
            src = f"{width}'d{constants[p.name]}"
        else:
            reg = "lfsr_x" if hi > 63 else "lfsr"
            src = f"{reg}[{hi}:{lo}]" if width > 1 else f"{reg}[{lo}]"
        conns.append(f"    .{p.name}({src})")
    for p in outs:
        conns.append(f"    .{p.name}(o_{p.name})")

    # Assert before emitting: a harness that is wrong is worse than no harness,
    # because it produces numbers that look measured.
    _check_connections(pl, [c.split(".", 1)[1].split("(")[0] for c in conns])

    pstr = ""
    if params:
        pstr = " #(\n" + ",\n".join(f"    .{k}({v})" for k, v in sorted(params.items())) + "\n  )"

    # Blocking chain seeded from the REGISTER, not from `acc` itself: folding
    # `acc` into `acc` in an always_comb is a combinational loop, not a fold.
    # One rotate-xor step per 64-bit CHUNK of each output. A single
    # `64'(o_x)` truncates, so every bit above 63 of a wide bus used to be
    # invisible to the oracle.
    steps = []
    for p in outs:
        chunks = _chunks(p.width)
        for lo, hi in chunks:
            val = f"o_{p.name}" if len(chunks) == 1 else f"o_{p.name}[{hi}:{lo}]"
            steps.append(f"      acc = {{acc[62:0], acc[63]}} ^ 64'({val});")
    fold = "\n".join(["      acc = sum;"] + steps)
    lfsr_x = _lfsr_x_sv(copies) if copies else ""

    return f"""{_HEAD_SV}//
// Wraps {top} with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module {top}_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
{chr(10).join(decls)}

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
{fold}
  end
{lfsr_x}
  {top}{pstr} dut (
{(',' + chr(10)).join(conns)}
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd{SEED};
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
"""


# ------------------------------------------------------ Pyrope harness ------
# Pyrope binds a clock/reset by TYPE (`clk:Clock`, `rst:Reset`), never by name
# (livehd qa.md section 6). The harness therefore declares a real `clk:Clock`
# and `rst:Reset` and binds EVERY DUT clock/reset explicitly from them, with the
# conversion the DUT's declared port type needs. Leaving one unbound used to be
# the silent wrong-checksum trap: a harness whose `rst` was a `u1` DATA input
# had no Reset of its own, LiveHD minted `reset:Reset` for it, the DUT's
# `rst:Reset` auto-wired to that minted reset, and nothing ever drove it.


def _split_top_level(text: str) -> list[str]:
    """Split a port list at the commas outside any () or [].

    `<`/`>` are not brackets here: a port type or default may hold a shift or
    comparison (`a:unsigned(bits=N>>1)`, `i:0..<8`), and a generic argument
    list with a comma needs parentheses in a port type anyway.
    """
    items, depth, cur = [], 0, []
    for ch in text:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            items.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    if "".join(cur).strip():
        items.append("".join(cur))
    return items


def _balanced(text: str, start: int, open_ch: str = "(", close_ch: str = ")") -> tuple[str, int]:
    """The text inside the bracket opening at `start`, and the index after it.

    Only `open_ch`/`close_ch` nest, except for `<`: a generic list's operators
    sit inside parentheses (`<N=(A>>1)>`), so parentheses nest there too.
    """
    depth, paren = 0, 0
    for i in range(start, len(text)):
        ch = text[i]
        if open_ch == "<" and ch in "()":
            paren += 1 if ch == "(" else -1
        elif paren:
            continue
        elif ch == open_ch:
            depth += 1
        elif ch == close_ch:
            depth -= 1
            if depth == 0:
                return text[start + 1 : i], i + 1
    return text[start + 1 :], len(text)


def _pyrope_signature_start(prp_text: str, top: str) -> int | None:
    """Index of the `(` opening a `mod` or `comb` top's input list, or None.

    Skips what may sit between the name and the inputs, in either order: a
    lambda attribute list (`::[timecheck=false]`) and a generic list
    (`<N=4, M=(N>>1)>`).
    """
    import re

    for m in re.finditer(rf"\b(?:mod|comb)\s+{re.escape(top)}\b", prp_text):
        i = m.end()
        while True:
            while i < len(prp_text) and prp_text[i].isspace():
                i += 1
            if prp_text.startswith("::[", i):
                i = _balanced(prp_text, i + 2, "[", "]")[1]
            elif prp_text.startswith("<", i):
                i = _balanced(prp_text, i, "<", ">")[1]
            else:
                break
        if prp_text.startswith("(", i):
            return i
    return None


def pyrope_port_types(prp_text: str, top: str) -> dict[str, str] | None:
    """Each port of the Pyrope DUT `top` -> its declared type text (`Clock`,
    `Reset`, `U1`, `Bool`, `Unsigned(bits=8)`, ...; "" when untyped).

    None when the source has no `mod` or `comb` top signature: the generator then
    falls back to the Verilog port list alone (clocks as `Clock`, resets as
    `Reset`). The Verilog list cannot tell a `Bool` from a `U1`, a data `rst`
    from a `Reset`, or say that a combinational Pyrope top dropped its unused
    clk/rst, so the Pyrope signature decides how each port is bound.
    """
    import re

    start = _pyrope_signature_start(prp_text, top)
    if start is None:
        return None
    ins, after = _balanced(prp_text, start)
    lists = [ins]
    arrow = re.match(r"\s*->\s*\(", prp_text[after:])
    if arrow:
        lists.append(_balanced(prp_text, after + arrow.end() - 1)[0])
    out: dict[str, str] = {}
    for plist in lists:
        for item in _split_top_level(re.sub(r"//[^\n]*", "", plist)):
            name, sep, ty = item.partition(":")
            words = name.split()
            name = words[-1].strip("`") if words else ""
            if not name:
                continue
            # `x:U8@[0] = 3` / `x:Reset:[attr]`: the type is the text before
            # any timing, attribute or default.
            ty = re.split(r"@|=|:\[", ty)[0].strip() if sep else ""
            out[name] = ty
    return out


def pyrope_bool_ports(prp_text: str, top: str) -> set[str]:
    """The ports the Pyrope DUT `top` declares `Bool`.

    Booleans never mix with integers at a port (user ruling 2026-09-27): an LFSR
    bit bound to a `Bool` input needs `Bool(...)`, and a `Bool` output folded
    into the integer checksum needs `U1(...)`. Kept for callers that predate
    pyrope_port_types; harness_prp reads the Bool ports from `port_types`.
    """
    types = pyrope_port_types(prp_text, top) or {}
    return {n for n, t in types.items() if t in ("Bool", "bool", "boolean")}


def harness_prp(
    pl: PortList,
    input_constants: dict[str, int] | None = None,
    bool_ports: set[str] | None = None,
    port_types: dict[str, str] | None = None,
) -> str:
    """The Pyrope harness. `port_types` (pyrope_port_types of the DUT source)
    picks each port's binding; without it every Verilog clock is taken to be a
    `Clock` and every reset a `Reset`, which is what LiveHD emits for a port
    that really clocks or resets state."""
    top = pl.top
    stim = _slices(pl.inputs)
    outs = pl.outputs
    constants = _input_constants(pl, input_constants)
    types = port_types
    bools = set(bool_ports or set())
    if types is not None:
        bools |= {n for n, t in types.items() if t in ("Bool", "bool", "boolean")}

    def declared(name: str) -> bool:
        # A combinational Pyrope top may DROP the clk/rst the Verilog only
        # carries for its interface (unconnected clock/reset are not an LEC
        # difference): bind only what the DUT declares.
        return types is None or name in types

    args = []
    # Every clock and reset is bound EXPLICITLY from the harness's own
    # `clk:Clock` / `rst:Reset`: no reliance on auto-wiring (a DUT with two
    # Clock inputs must be bound anyway), and the conversion follows the DUT's
    # declared type. An active-low Verilog reset (`rst_n`) gets the inverted
    # level, like `~rst` on the SV side; in Pyrope its polarity lives on the
    # DUT's registers (`negreset=true`), so the signal itself is just `not rst`.
    for c in pl.clocks:
        if not declared(c.name):
            continue
        ty = (types or {}).get(c.name, "Clock")
        if ty in ("Clock", ""):
            args.append(f"{pid(c.name)}=clk")
        elif c.name in bools:
            # A Clock is never data (`Bool(clk)` is an error). A Pyrope DUT that
            # declares its Verilog clock as data clocks its state from a minted
            # clock instead; this input is then a plain bit, held low.
            args.append(f"{pid(c.name)}=false")
        else:
            args.append(f"{pid(c.name)}=0")
    for r in pl.resets:
        if not declared(r.name):
            continue
        ty = (types or {}).get(r.name, "Reset")
        level = "not rst" if r.active_low_reset else "rst"
        if ty in ("Reset", "") or r.name in bools:
            args.append(f"{pid(r.name)}={level}")  # a Reset is Bool-like: no cast either way
        else:
            args.append(f"{pid(r.name)}=U1({level})")
    for p, _, _ in stim:
        ty = (types or {}).get(p.name, "")
        if ty in ("Clock", "Reset"):
            raise HarnessError(
                f"{pl.top}: the Pyrope DUT declares `{p.name}:{ty}`, but the Verilog port list "
                "treats it as data (its name is not a clock/reset name); the harnesses would "
                "drive it differently"
            )
    copies = _lfsr_x_copies(stim, constants)
    for p, lo, hi in stim:
        if p.name in constants:
            value = constants[p.name]
            if p.name in bools:
                args.append(f"{pid(p.name)}={'true' if value else 'false'}")
            else:
                args.append(f"{pid(p.name)}={value}")
        else:
            reg = "lfsr_x" if hi > 63 else "lfsr"
            # A signed port takes the SAME bits, reinterpreted: `#sext` reads
            # the window as two's complement, which is what the SV side's
            # unsigned wire into a signed port means.
            if p.signed:
                args.append(f"{pid(p.name)}={reg}#sext[{lo}..={hi}]")
            elif hi > lo:
                args.append(f"{pid(p.name)}={reg}#[{lo}..={hi}]")
            elif p.name in bools:
                args.append(f"{pid(p.name)}=Bool({reg}#[{lo}])")
            else:
                args.append(f"{pid(p.name)}={reg}#[{lo}]")
    # A single-output lambda auto-unwraps its result tuple; more than one must
    # be DESTRUCTURED at the call. `const r = dut(...)` on a multi-output call
    # is rejected outright ("a call returning multiple outputs cannot bind to
    # the single variable `r`"), and while a `mod` instance used to bind that
    # way, a multi-output `comb` never did -- so this emits the one spelling
    # both accept. Getting it wrong is the most likely way a generated Pyrope
    # harness fails to compile, so it is decided here, once.
    # No cast on the read: Pyrope integers are unlimited precision and `acc` is
    # declared U64 with `wrap`, so the narrowing is explicit at the assignment.
    #
    # The destructured names become harness locals, so an output sharing a name
    # with one of the harness's own (`lfsr`, `sum`, `acc`, ...) would shadow it.
    # Prefix the whole tuple in that case rather than only the clashing member:
    # a mixed spelling is far easier to misread later than a uniform one.
    if len(outs) == 1:
        bind, reads = "r", ["r"]
    else:
        names = [pid(p.name) for p in outs]
        if set(names) & _HARNESS_LOCALS:
            names = [f"o_{n}" for n in names]
        bind, reads = f"({', '.join(names)})", names
    call = (f"  const {bind} = dut({', '.join(args)})" if args
            else f"  const {bind} = dut()")
    steps = []
    for p, expr in zip(outs, reads):
        chunks = _chunks(p.width)
        for lo, hi in chunks:
            # A signed output is folded as its raw bits: the SV harness reads it
            # through an unsigned `o_` wire, i.e. zero-extended. A `Bool` output
            # is a bit only through `U1(...)` (true == 1).
            whole = len(chunks) == 1 and not p.signed
            if p.name in bools:
                val = f"U1({expr})"
            else:
                val = expr if whole else f"{expr}#[{lo}..={hi}]"
            steps.append(f"  wrap acc = ((acc << 1) | acc#[63]) ^ {val}")
    fold = "\n".join(steps) or "  wrap acc = (acc << 1) | acc#[63]"
    lfsr_x = _lfsr_x_prp(copies) if copies else ""

    return f"""{_HEAD_PRP}//
// The Pyrope twin of {top}_harness.sv: same LFSR, same fold, same seed, so all
// three simulators must agree on `checksum` or the test fails.
//
// This is GENERATED from the DUT's port list and its Pyrope signature. A
// hand-written idiomatic Pyrope module may present a different interface;
// adjusting this file is part of promoting the test to status.pyrope =
// "idiomatic".
// `file.entity`: import("{top}") names the FILE, and calling it fails with
// "call to undefined function". The module inside it is {top}.{top}.
const dut = import("{top}.{top}")

// `clk:Clock` / `rst:Reset` are this harness's clock and reset: its two
// registers bind to them implicitly (the `= value` is the reset value, like
// the SV `if (rst)` branch), and every DUT clock/reset is bound from them.
pub mod {top}_harness(clk:Clock, rst:Reset) -> (checksum:U64@[0]) {{
  reg lfsr:U64 = {SEED}
  reg sum:U64  = 0

  checksum = sum

  mut nxt:U64 = lfsr
  wrap nxt = nxt ^ (nxt << 13)
  wrap nxt = nxt ^ (nxt >> 7)
  wrap nxt = nxt ^ (nxt << 17)
{lfsr_x}
{call}

  mut acc:U64 = sum
{fold}

  lfsr = nxt
  sum  = acc
}}
"""


# ------------------------------------------------------ Pyrope driver -------
def tb_prp(pl: PortList, cycles: int) -> str:
    top = pl.top
    return f"""{_HEAD_PRP}//
// `lhd sim` driver. The design input is supplied ahead of this file by the
// flow, so `import("lg:...")` names whichever library was just compiled --
// the Pyrope tree under sim_lhd_pyrope, the Verilog one under sim_lhd_verilog.
// Identical driver, identical work, either way.
const dut = import("lg:{top}_harness")

test bench.run(cycles:U32={cycles}) {{
  mut acc = dut
  mut result:U64 = 0

  // The tick's minted `clock:Clock` auto-wires to the harness's single Clock
  // input; a Bool drives its Reset without a cast. Never poke the clock.
  tick cycles {{
    acc.rst = clock < {RESET_CYCLES}
    step
    result = acc.checksum
  }}

  puts("LHDTRACK-DONE cycles={{cycles}} checksum={{result}}")
}}
"""


# ---------------------------------------------------- verilator driver ------
def tb_verilator(pl: PortList, cycles: int) -> str:
    top = pl.top
    return f"""// Generated by tools/gen_testbench.py -- {MARKER}. Simulation only.
//
// The C++ twin of {top}_tb.prp: same cycle count, same reset schedule, same
// printed line. Both must fold the same checksum or the test fails -- that is
// what stops a miscompile from being reported as a speedup.
//
// No --trace anywhere: a VCD writer inside the measured interval turns a
// simulation benchmark into a filesystem benchmark.
#include "V{top}_harness.h"
#include "verilated.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

int main(int argc, char **argv) {{
  Verilated::commandArgs(argc, argv);

  uint64_t cycles = {cycles};
  for (int i = 1; i < argc; ++i) {{
    if (!std::strncmp(argv[i], "+cycles=", 8)) {{
      cycles = std::strtoull(argv[i] + 8, nullptr, 10);
      break;
    }} else if (!std::strcmp(argv[i], "--cycles") && i + 1 < argc) {{
      cycles = std::strtoull(argv[++i], nullptr, 10);
      break;
    }}
  }}

  auto *top = new V{top}_harness;

  for (uint64_t c = 0; c < cycles; ++c) {{
    top->rst = (c < {RESET_CYCLES}) ? 1 : 0;
    top->clk = 0;
    top->eval();
    top->clk = 1;
    top->eval();
  }}
  top->final();

  std::printf("LHDTRACK-DONE cycles=%llu checksum=%llu\\n",
              (unsigned long long)cycles,
              (unsigned long long)top->checksum);

  delete top;
  return 0;
}}
"""
