"""Generate the four simulation files of a test, from one port list.

    sim/<top>_harness.sv     RTL harness: LFSR stimulus + checksum, wraps the SV DUT
    sim/<top>_harness.prp    the same harness in Pyrope, wrapping the Pyrope DUT
    sim/<top>_tb.prp         `lhd sim` driver: tick N, read checksum, print
    sim/<top>_tb_verilator.cpp   the C++ twin of that driver

WHY THE STIMULUS LIVES IN RTL. The obvious design puts the LFSR in the
testbench and drives ports from software. That makes the three simulators do
*different* work -- verilator's C++ harness against `lhd sim`'s generated
driver -- and it forces the generator to know each port's exact type in each
language, which is where a generated testbench actually breaks.

Putting the stimulus and the checksum inside the harness RTL instead means both
tools COMPILE AND SIMULATE THE SAME STATE MACHINE, and the driver shrinks to
"tick N times, read one 64-bit output". The interface between driver and design
is then a single unsigned integer, which cannot be mistyped.

The cost is dilution: on a very small DUT the harness is a measurable share of
the simulated work, so absolute cycles/s understates the tool. Ratios between
the three simulators stay valid, which is what the tracker reports.

WHY THE CHECKSUM AVOIDS MULTIPLY. A rotate-and-xor fold costs a few gates; a
64x64 multiply would dwarf most blocks in this corpus and turn every row into a
multiplier benchmark.

A GENERATED HARNESS IS A STARTING POINT. The Pyrope half in particular assumes
the DUT is a `mod` with named ports; a hand-written idiomatic Pyrope module may
present a different interface, and adjusting the harness is part of promoting a
test to `status.pyrope = "idiomatic"`.
"""

from __future__ import annotations

from pathlib import Path

from ports import CLOCK_RE, RESET_RE, Port, PortList

MARKER = "lhdtrack-generated"
SEED = 2611923443488327891  # 0x243F6A8885A308D3 -- the fractional bits of pi
RESET_CYCLES = 4

_HEAD_SV = f"// Generated by tools/gen_testbench.py -- {MARKER}. Simulation only.\n"
_HEAD_PRP = f"// Generated by tools/gen_testbench.py -- {MARKER}. Simulation only.\n"


# Pyrope keywords and operators. A port named `in`, `out` is fine but `in` is
# the membership operator, so any identifier landing in this set must be
# backtick-escaped -- Pyrope's documented escape for exactly this case.
_PRP_KEYWORDS = {
    "and", "assert", "assume", "break", "case", "comb", "comptime", "const",
    "continue", "does", "elif", "else", "enum", "equals", "false", "fluid",
    "for", "formal", "has", "if", "implies", "import", "in", "is", "loop",
    "match", "mod", "mut", "nil", "not", "or", "past", "pipe", "pub", "ref",
    "reg", "return", "sat", "self", "stage", "step", "test", "tick", "true",
    "type", "while", "wire", "wrap",
}


def pid(name: str) -> str:
    """A port name, safe to use as a Pyrope identifier."""
    return f"`{name}`" if name in _PRP_KEYWORDS else name


def is_generated(path: Path) -> bool:
    return path.exists() and MARKER in path.read_text(errors="replace")


# --------------------------------------------------------------- slicing ----
def _slices(inputs: list[Port]) -> list[tuple[Port, int, int]]:
    """Assign each stimulus input a disjoint window of the 64-bit LFSR.

    Disjoint so two inputs never receive correlated bits, and wrapped modulo 64
    so a design with more than 64 bits of input still gets every port driven.
    """
    out, bit = [], 0
    for p in inputs:
        width = max(1, p.width)
        lo = bit % 64
        hi = min(lo + width - 1, 63)
        out.append((p, lo, hi))
        bit += width
    return out


# ---------------------------------------------------------- SV harness ------
class HarnessError(RuntimeError):
    """The generated harness would not faithfully exercise the DUT."""


def _check_connections(pl: PortList, connected: list[str]) -> None:
    """Every DUT port is wired exactly once, and no clock is driven by data.

    THE CHECKSUM ORACLE CANNOT CATCH A BAD HARNESS. All three simulators share
    it, so if the harness clocks a design from a random LFSR bit -- which this
    generator did until the clock pattern was widened to catch `wr_clk` -- all
    three agree on the same nonsense and the oracle reports nothing. Twice now
    a harness bug has hidden behind that agreement, so the harness checks
    itself instead of relying on a downstream comparison that structurally
    cannot see it.
    """
    want = {p.name for p in pl.ports}
    got = list(connected)
    missing = want - set(got)
    if missing:
        raise HarnessError(
            f"{pl.top}: harness leaves {sorted(missing)} unconnected -- an undriven "
            "clock or reset simulates against a floating signal"
        )
    dupes = {n for n in got if got.count(n) > 1}
    if dupes:
        raise HarnessError(f"{pl.top}: harness wires {sorted(dupes)} more than once")
    stim = {p.name for p in pl.inputs}
    misdriven = {n for n in stim if CLOCK_RE.match(n) or RESET_RE.match(n)}
    if misdriven:
        raise HarnessError(
            f"{pl.top}: {sorted(misdriven)} would be driven by the stimulus LFSR "
            "but is named like a clock or reset"
        )


def harness_sv(pl: PortList, params: dict) -> str:
    top = pl.top
    stim = _slices(pl.inputs)
    outs = pl.outputs

    decls = [f"  logic [{max(1, p.width)-1}:0] o_{p.name};" for p in outs]

    conns = []
    # EVERY clock and reset port, not just the first. A multi-domain block
    # declares several (`wr_clk`/`rd_clk`), and connecting only one leaves the
    # others floating -- which either fails elaboration or, worse, simulates
    # against an undriven clock.
    #
    # They are all tied to the SAME clk/rst, which makes a multi-domain design
    # synchronous for this benchmark. That is a real simplification: a CDC block
    # wired this way does not exercise its crossing. It is the right default
    # here -- the harness measures synthesis and simulation throughput, not
    # protocol behaviour -- but a CDC test that wants its crossing exercised
    # needs a hand-written harness.
    for c in pl.clocks:
        conns.append(f"    .{c.name}(clk)")
    for r in pl.resets:
        conns.append(f"    .{r.name}({'~rst' if r.active_low_reset else 'rst'})")
    for p, lo, hi in stim:
        width = max(1, p.width)
        src = f"lfsr[{hi}:{lo}]" if width > 1 else f"lfsr[{lo}]"
        if hi - lo + 1 < width:  # the window was clipped at bit 63
            src = f"{{{width - (hi - lo + 1)}'d0, {src}}}"
        conns.append(f"    .{p.name}({src})")
    for p in outs:
        conns.append(f"    .{p.name}(o_{p.name})")

    # Assert before emitting: a harness that is wrong is worse than no harness,
    # because it produces numbers that look measured.
    _check_connections(pl, [c.split(".", 1)[1].split("(")[0] for c in conns])

    pstr = ""
    if params:
        pstr = " #(\n" + ",\n".join(f"    .{k}({v})" for k, v in sorted(params.items())) + "\n  )"

    # Blocking chain seeded from the REGISTER, not from `acc` itself: folding
    # `acc` into `acc` in an always_comb is a combinational loop, not a fold.
    fold = "\n".join(
        ["      acc = sum;"]
        + [f"      acc = {{acc[62:0], acc[63]}} ^ 64'(o_{p.name});" for p in outs]
    )

    return f"""{_HEAD_SV}//
// Wraps {top} with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module {top}_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
{chr(10).join(decls)}

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
{fold}
  end

  {top}{pstr} dut (
{(',' + chr(10)).join(conns)}
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd{SEED};
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
"""


# ------------------------------------------------------ Pyrope harness ------
def harness_prp(pl: PortList) -> str:
    top = pl.top
    stim = _slices(pl.inputs)
    outs = pl.outputs

    args = []
    # Auto-emitted Pyrope keeps clk/rst as explicit ports (lhd emits
    # `mod X(clk:u1, rst:u1, ...)`), so they must be bound or the call fails
    # with "does not bind declared input 'clk'". Hand-written Pyrope leaves them
    # implicit and declares neither -- which is why this is driven by the port
    # list from the VERILOG, and why a hand-written module needs its harness
    # adjusted when it is promoted to `idiomatic`.
    for c in pl.clocks:
        args.append(f"{pid(c.name)}=0")
    for r in pl.resets:
        args.append(f"{pid(r.name)}=rst")
    for p, lo, hi in stim:
        args.append(
            f"{pid(p.name)}=lfsr#[{lo}..={hi}]" if hi > lo else f"{pid(p.name)}=lfsr#[{lo}]"
        )
    call = f"  const r = dut({', '.join(args)})" if args else "  const r = dut()"

    # A single-output lambda auto-unwraps its result tuple; more than one keeps
    # the field names. Getting this wrong is the most likely way a generated
    # Pyrope harness fails to compile, so it is decided here, once.
    # No cast on the read. `u64(x)` is not a built-in cast in this lhd build,
    # and none is needed: Pyrope integers are unlimited precision and `acc` is
    # declared u64 with `wrap`, so the narrowing is explicit at the assignment.
    if len(outs) == 1:
        reads = ["r"]
    else:
        reads = [f"r.{pid(p.name)}" for p in outs]
    fold = "\n".join(
        f"  wrap acc = ((acc << 1) | acc#[63]) ^ {expr}" for expr in reads
    ) or "  wrap acc = (acc << 1) | acc#[63]"

    return f"""{_HEAD_PRP}//
// The Pyrope twin of {top}_harness.sv: same LFSR, same fold, same seed, so all
// three simulators must agree on `checksum` or the test fails.
//
// This is GENERATED and assumes the DUT is a `mod` with these port names. A
// hand-written idiomatic Pyrope module may present a different interface;
// adjusting this file is part of promoting the test to status.pyrope =
// "idiomatic".
// `file.entity`: import("{top}") names the FILE, and calling it fails with
// "call to undefined function". The module inside it is {top}.{top}.
const dut = import("{top}.{top}")

pub mod {top}_harness(rst:u1) -> (checksum:u64@[0]) {{
  reg lfsr:u64 = {SEED}
  reg sum:u64  = 0

  checksum = sum

  mut nxt:u64 = lfsr
  wrap nxt = nxt ^ (nxt << 13)
  wrap nxt = nxt ^ (nxt >> 7)
  wrap nxt = nxt ^ (nxt << 17)

{call}

  mut acc:u64 = sum
{fold}

  if rst != 0 {{
    lfsr = {SEED}
    sum  = 0
  }} else {{
    lfsr = nxt
    sum  = acc
  }}
}}
"""


# ------------------------------------------------------ Pyrope driver -------
def tb_prp(pl: PortList, cycles: int) -> str:
    top = pl.top
    return f"""{_HEAD_PRP}//
// `lhd sim` driver. The design input is supplied ahead of this file by the
// flow, so `import("lg:...")` names whichever library was just compiled --
// the Pyrope tree under sim_lhd_pyrope, the Verilog one under sim_lhd_verilog.
// Identical driver, identical work, either way.
const dut = import("lg:{top}_harness")

test bench.run(cycles:u32={cycles}) {{
  mut acc = dut
  mut result:u64 = 0

  tick cycles {{
    // `u1(...)`, not `int(...)`: this lhd build removed the `int` cast in
    // favour of sized/sign-explicit ones.
    acc.rst = u1(clock < {RESET_CYCLES})
    step
    result = acc.checksum
  }}

  puts("LHDTRACK-DONE cycles={{}} checksum={{}}", cycles, result)
}}
"""


# ---------------------------------------------------- verilator driver ------
def tb_verilator(pl: PortList, cycles: int) -> str:
    top = pl.top
    return f"""// Generated by tools/gen_testbench.py -- {MARKER}. Simulation only.
//
// The C++ twin of {top}_tb.prp: same cycle count, same reset schedule, same
// printed line. Both must fold the same checksum or the test fails -- that is
// what stops a miscompile from being reported as a speedup.
//
// No --trace anywhere: a VCD writer inside the measured interval turns a
// simulation benchmark into a filesystem benchmark.
#include "V{top}_harness.h"
#include "verilated.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

int main(int argc, char **argv) {{
  Verilated::commandArgs(argc, argv);

  uint64_t cycles = {cycles};
  for (int i = 1; i < argc; ++i) {{
    if (!std::strcmp(argv[i], "--cycles") && i + 1 < argc) {{
      cycles = std::strtoull(argv[++i], nullptr, 10);
    }}
  }}

  auto *top = new V{top}_harness;

  for (uint64_t c = 0; c < cycles; ++c) {{
    top->rst = (c < {RESET_CYCLES}) ? 1 : 0;
    top->clk = 0;
    top->eval();
    top->clk = 1;
    top->eval();
  }}
  top->final();

  std::printf("LHDTRACK-DONE cycles=%llu checksum=%llu\\n",
              (unsigned long long)cycles,
              (unsigned long long)top->checksum);

  delete top;
  return 0;
}}
"""
