"""Generate `constraints/default.sdc`.

Exactly two shapes, decided by whether the top has a clock:

  sequential     create_clock on the real clock port, plus a false path from
                 reset -- see below
  combinational  a VIRTUAL clock plus set_input_delay / set_output_delay --
                 which is what OpenSTA needs before it will report an
                 input-to-output path at all

RESET IS EXCLUDED FROM TIMING. It arrives from a top-level port with no logic
in front of it and fans out to every register, so on any design with a short
datapath it wins the critical path with a number that describes the testbench
boundary rather than the design.

Both engines read this same file, which is what makes the OpenTimer/OpenSTA
correlation column a statement about the timers rather than about their inputs.

The period comes from lhdtrack.toml's [sdc].period, per technology. It is
deliberately uniform: a per-test hand-tuned period is more realistic but turns
~200 numbers into ~200 judgement calls, and a period chosen too loose makes a
test permanently uninformative. A test that genuinely needs its own constraints
checks in its own default.sdc and the generator leaves it alone.
"""

from __future__ import annotations

from pathlib import Path

from ports import PortList

HEADER = """# Generated by tools/gen_sdc.py -- do not edit.
# To use real constraints for this test, replace this file; the generator will
# not overwrite a file it did not write (see the marker line above).
"""

MARKER = "# lhdtrack-generated"


def generate(pl: PortList, period: float, unit: str = "ns") -> str:
    clk, rst = pl.clock, pl.reset
    lines = [
        HEADER.rstrip(),
        MARKER,
        f"# Period {period:g} {unit} -- expressed in THIS library's time unit, which is",
        f"# why constraints are generated per technology (sky130 is 1ns, ASAP7 is 1ps).",
        "",
    ]

    if clk is not None:
        lines += [
            f"create_clock -name clk -period {period} [get_ports {clk.name}]",
            "",
            "# ZERO I/O budget, deliberately. An external delay is part of the arrival",
            "# time OpenSTA reports but NOT of the path delay lhd's OpenTimer reports,",
            "# so any non-zero budget shows up as pure disagreement between the two",
            "# timers. A 20% budget made them look 98% apart on br_delay, whose worst",
            "# path is a zero-logic feedthrough: every nanosecond of the 4.0 ns",
            "# 'critical path' was the budget itself. At zero, both timers measure the",
            "# same thing -- the longest path through the design.",
            # `all_inputs -no_clocks`, not `remove_from_collection`: the latter
            # is a Synopsys collection command that OpenSTA does not implement
            # ("invalid command name"), and a constraint file that only one
            # timer can read defeats the whole point of timing both.
            "set_input_delay  -clock clk 0.0 [all_inputs -no_clocks]",
            "set_output_delay -clock clk 0.0 [all_outputs]",
        ]
        if rst is not None:
            lines += [
                "",
                "# RESET IS A FALSE PATH. Reset arrives straight from a top-level port",
                "# with no logic in front of it, so its arrival time is a property of",
                "# the testbench boundary rather than of the design -- and because it",
                "# fans out to every register, it wins the critical path on any design",
                "# whose real datapath is short. On br_delay it reported 1.545 ns of",
                "# 'critical path' that was entirely reset distribution, hiding the",
                "# register-to-register path this benchmark exists to measure.",
                "#",
                "# In silicon a synchronous reset IS a real path; it is excluded here",
                "# because the corpus compares DATAPATH quality, and a reset tree is a",
                "# global-routing problem solved after synthesis. A test that needs it",
                "# timed checks in its own constraints file.",
                f"set_false_path -from [get_ports {rst.name}]",
            ]
    else:
        lines += [
            "# Combinational top: no clock port exists, so the timer is given a VIRTUAL",
            "# clock. Without one OpenSTA reports no paths at all and the whole",
            "# input-to-output cone would silently go unmeasured.",
            f"create_clock -name vclk -period {period}",
            "",
            f"set_input_delay  -clock vclk 0.0 [all_inputs]",
            f"set_output_delay -clock vclk 0.0 [all_outputs]",
        ]

    lines += [
        "",
        "# No multicycle paths, and no false paths beyond reset above: every other",
        "# path in these blocks is a real one, and an exception added to make a",
        "# number look better is a number that lies.",
        "",
    ]
    return "\n".join(lines)


def is_generated(path: Path) -> bool:
    """Did WE write this file? A hand-written SDC is never overwritten."""
    return path.exists() and MARKER in path.read_text(errors="replace")
