// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_cdc_fifo_flops_push_credit with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_cdc_fifo_flops_push_credit_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_push_receiver_in_reset;
  logic [0:0] o_push_credit;
  logic [0:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [0:0] o_push_full;
  logic [5:0] o_push_slots;
  logic [5:0] o_credit_count_push;
  logic [5:0] o_credit_available_push;
  logic [0:0] o_pop_empty;
  logic [5:0] o_pop_items;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_receiver_in_reset);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_credit);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_full);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_slots);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_count_push);
      acc = {acc[62:0], acc[63]} ^ 64'(o_credit_available_push);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_items);
  end

  br_cdc_fifo_flops_push_credit dut (
    .push_clk(clk),
    .pop_clk(clk),
    .push_rst(rst),
    .pop_rst(rst),
    .push_sender_in_reset(rst),
    .push_credit_stall(lfsr[0]),
    .push_valid(lfsr[1]),
    .push_data({2'd0, lfsr[63:2]}),
    .pop_ready(lfsr[2]),
    .credit_initial_push(lfsr[8:3]),
    .credit_withhold_push(lfsr[14:9]),
    .push_receiver_in_reset(o_push_receiver_in_reset),
    .push_credit(o_push_credit),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .push_full(o_push_full),
    .push_slots(o_push_slots),
    .credit_count_push(o_credit_count_push),
    .credit_available_push(o_credit_available_push),
    .pop_empty(o_pop_empty),
    .pop_items(o_pop_items)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
