// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axil_split with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axil_split_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_root_awready;
  logic [0:0] o_root_wready;
  logic [1:0] o_root_bresp;
  logic [0:0] o_root_bvalid;
  logic [0:0] o_root_arready;
  logic [31:0] o_root_rdata;
  logic [1:0] o_root_rresp;
  logic [0:0] o_root_ruser;
  logic [0:0] o_root_rvalid;
  logic [31:0] o_trunk_awaddr;
  logic [2:0] o_trunk_awprot;
  logic [0:0] o_trunk_awuser;
  logic [0:0] o_trunk_awvalid;
  logic [31:0] o_trunk_wdata;
  logic [3:0] o_trunk_wstrb;
  logic [0:0] o_trunk_wuser;
  logic [0:0] o_trunk_wvalid;
  logic [0:0] o_trunk_bready;
  logic [31:0] o_trunk_araddr;
  logic [2:0] o_trunk_arprot;
  logic [0:0] o_trunk_aruser;
  logic [0:0] o_trunk_arvalid;
  logic [0:0] o_trunk_rready;
  logic [31:0] o_branch_awaddr;
  logic [2:0] o_branch_awprot;
  logic [0:0] o_branch_awuser;
  logic [0:0] o_branch_awvalid;
  logic [31:0] o_branch_wdata;
  logic [3:0] o_branch_wstrb;
  logic [0:0] o_branch_wuser;
  logic [0:0] o_branch_wvalid;
  logic [0:0] o_branch_bready;
  logic [31:0] o_branch_araddr;
  logic [2:0] o_branch_arprot;
  logic [0:0] o_branch_aruser;
  logic [0:0] o_branch_arvalid;
  logic [0:0] o_branch_rready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_ruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_root_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_bready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_araddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_arprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_aruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_arvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_trunk_rready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_bready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_araddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_arprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_aruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_arvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_branch_rready);
  end

  br_amba_axil_split #(
    .AddrWidth(32),
    .DataWidth(32),
    .MaxOutstandingReads(4),
    .MaxOutstandingWrites(4),
    .NormalizeBranchAddress(0),
    .NumBranchAddrRanges(1)
  ) dut (
    .clk(clk),
    .rst(rst),
    .branch_start_addr(lfsr[31:0]),
    .branch_end_addr(lfsr[63:32]),
    .root_awaddr(lfsr[31:0]),
    .root_awprot(lfsr[34:32]),
    .root_awuser(lfsr[35]),
    .root_awvalid(lfsr[36]),
    .root_wdata({5'd0, lfsr[63:37]}),
    .root_wstrb(lfsr[8:5]),
    .root_wuser(lfsr[9]),
    .root_wvalid(lfsr[10]),
    .root_bready(lfsr[11]),
    .root_araddr(lfsr[43:12]),
    .root_arprot(lfsr[46:44]),
    .root_aruser(lfsr[47]),
    .root_arvalid(lfsr[48]),
    .root_rready(lfsr[49]),
    .trunk_awready(lfsr[50]),
    .trunk_wready(lfsr[51]),
    .trunk_bresp(lfsr[53:52]),
    .trunk_bvalid(lfsr[54]),
    .trunk_arready(lfsr[55]),
    .trunk_rdata({24'd0, lfsr[63:56]}),
    .trunk_rresp(lfsr[25:24]),
    .trunk_ruser(lfsr[26]),
    .trunk_rvalid(lfsr[27]),
    .branch_awready(lfsr[28]),
    .branch_wready(lfsr[29]),
    .branch_bresp(lfsr[31:30]),
    .branch_bvalid(lfsr[32]),
    .branch_arready(lfsr[33]),
    .branch_rdata({2'd0, lfsr[63:34]}),
    .branch_rresp(lfsr[3:2]),
    .branch_ruser(lfsr[4]),
    .branch_rvalid(lfsr[5]),
    .root_awready(o_root_awready),
    .root_wready(o_root_wready),
    .root_bresp(o_root_bresp),
    .root_bvalid(o_root_bvalid),
    .root_arready(o_root_arready),
    .root_rdata(o_root_rdata),
    .root_rresp(o_root_rresp),
    .root_ruser(o_root_ruser),
    .root_rvalid(o_root_rvalid),
    .trunk_awaddr(o_trunk_awaddr),
    .trunk_awprot(o_trunk_awprot),
    .trunk_awuser(o_trunk_awuser),
    .trunk_awvalid(o_trunk_awvalid),
    .trunk_wdata(o_trunk_wdata),
    .trunk_wstrb(o_trunk_wstrb),
    .trunk_wuser(o_trunk_wuser),
    .trunk_wvalid(o_trunk_wvalid),
    .trunk_bready(o_trunk_bready),
    .trunk_araddr(o_trunk_araddr),
    .trunk_arprot(o_trunk_arprot),
    .trunk_aruser(o_trunk_aruser),
    .trunk_arvalid(o_trunk_arvalid),
    .trunk_rready(o_trunk_rready),
    .branch_awaddr(o_branch_awaddr),
    .branch_awprot(o_branch_awprot),
    .branch_awuser(o_branch_awuser),
    .branch_awvalid(o_branch_awvalid),
    .branch_wdata(o_branch_wdata),
    .branch_wstrb(o_branch_wstrb),
    .branch_wuser(o_branch_wuser),
    .branch_wvalid(o_branch_wvalid),
    .branch_bready(o_branch_bready),
    .branch_araddr(o_branch_araddr),
    .branch_arprot(o_branch_arprot),
    .branch_aruser(o_branch_aruser),
    .branch_arvalid(o_branch_arvalid),
    .branch_rready(o_branch_rready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
