// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axil_msi with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axil_msi_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_error;
  logic [31:0] o_init_awaddr;
  logic [0:0] o_init_awvalid;
  logic [31:0] o_init_wdata;
  logic [3:0] o_init_wstrb;
  logic [0:0] o_init_wvalid;
  logic [0:0] o_init_bready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_error);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_bready);
  end

  br_amba_axil_msi #(
    .AddrWidth(32),
    .DataWidth(32),
    .DeviceIdWidth(16),
    .EventIdWidth(16),
    .NumInterrupts(4),
    .NumMsiDestAddr(1),
    .ThrottleCntrWidth(4)
  ) dut (
    .clk(clk),
    .rst(rst),
    .irq(lfsr[3:0]),
    .msi_dest_addr(lfsr[35:4]),
    .msi_enable(lfsr[39:36]),
    .msi_dest_idx(lfsr[43:40]),
    .device_id_per_irq({44'd0, lfsr[63:44]}),
    .event_id_per_irq({44'd0, lfsr[63:44]}),
    .throttle_en(lfsr[44]),
    .throttle_cntr_threshold(lfsr[48:45]),
    .init_awready(lfsr[49]),
    .init_wready(lfsr[50]),
    .init_bresp(lfsr[52:51]),
    .init_bvalid(lfsr[53]),
    .error(o_error),
    .init_awaddr(o_init_awaddr),
    .init_awvalid(o_init_awvalid),
    .init_wdata(o_init_wdata),
    .init_wstrb(o_init_wstrb),
    .init_wvalid(o_init_wvalid),
    .init_bready(o_init_bready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
