// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_fifo_shared_pstatic_flops with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_fifo_shared_pstatic_flops_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_config_error;
  logic [0:0] o_push_ready;
  logic [1:0] o_push_full;
  logic [1:0] o_pop_valid;
  logic [63:0] o_pop_data;
  logic [1:0] o_pop_empty;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_config_error);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_ready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_push_full);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_valid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_data);
      acc = {acc[62:0], acc[63]} ^ 64'(o_pop_empty);
  end

  br_fifo_shared_pstatic_flops dut (
    .clk(clk),
    .rst(rst),
    .config_base(lfsr[9:0]),
    .config_bound(lfsr[19:10]),
    .push_valid(lfsr[20]),
    .push_data(lfsr[52:21]),
    .push_fifo_id(lfsr[53]),
    .pop_ready(lfsr[55:54]),
    .config_error(o_config_error),
    .push_ready(o_push_ready),
    .push_full(o_push_full),
    .pop_valid(o_pop_valid),
    .pop_data(o_pop_data),
    .pop_empty(o_pop_empty)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
