// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axi_shrinker with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axi_shrinker_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_wide_awready;
  logic [0:0] o_wide_wready;
  logic [3:0] o_wide_bid;
  logic [0:0] o_wide_buser;
  logic [1:0] o_wide_bresp;
  logic [0:0] o_wide_bvalid;
  logic [0:0] o_wide_arready;
  logic [3:0] o_wide_rid;
  logic [63:0] o_wide_rdata;
  logic [0:0] o_wide_ruser;
  logic [1:0] o_wide_rresp;
  logic [0:0] o_wide_rlast;
  logic [0:0] o_wide_rvalid;
  logic [31:0] o_narrow_awaddr;
  logic [3:0] o_narrow_awid;
  logic [7:0] o_narrow_awlen;
  logic [2:0] o_narrow_awsize;
  logic [1:0] o_narrow_awburst;
  logic [2:0] o_narrow_awprot;
  logic [0:0] o_narrow_awuser;
  logic [0:0] o_narrow_awvalid;
  logic [31:0] o_narrow_wdata;
  logic [3:0] o_narrow_wstrb;
  logic [0:0] o_narrow_wuser;
  logic [0:0] o_narrow_wlast;
  logic [0:0] o_narrow_wvalid;
  logic [0:0] o_narrow_bready;
  logic [31:0] o_narrow_araddr;
  logic [3:0] o_narrow_arid;
  logic [7:0] o_narrow_arlen;
  logic [2:0] o_narrow_arsize;
  logic [1:0] o_narrow_arburst;
  logic [2:0] o_narrow_arprot;
  logic [0:0] o_narrow_aruser;
  logic [0:0] o_narrow_arvalid;
  logic [0:0] o_narrow_rready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_bid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_buser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_rid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_ruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_rlast);
      acc = {acc[62:0], acc[63]} ^ 64'(o_wide_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awlen);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awsize);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awburst);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_wlast);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_bready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_araddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_arid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_arlen);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_arsize);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_arburst);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_arprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_aruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_arvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_narrow_rready);
  end

  br_amba_axi_shrinker dut (
    .clk(clk),
    .rst(rst),
    .wide_awaddr(lfsr[31:0]),
    .wide_awid(lfsr[35:32]),
    .wide_awlen(lfsr[43:36]),
    .wide_awsize(lfsr[46:44]),
    .wide_awburst(lfsr[48:47]),
    .wide_awprot(lfsr[51:49]),
    .wide_awuser(lfsr[52]),
    .wide_awvalid(lfsr[53]),
    .wide_wdata({54'd0, lfsr[63:54]}),
    .wide_wstrb(lfsr[61:54]),
    .wide_wuser(lfsr[62]),
    .wide_wlast(lfsr[63]),
    .wide_wvalid(lfsr[0]),
    .wide_bready(lfsr[1]),
    .wide_araddr(lfsr[33:2]),
    .wide_arid(lfsr[37:34]),
    .wide_arlen(lfsr[45:38]),
    .wide_arsize(lfsr[48:46]),
    .wide_arburst(lfsr[50:49]),
    .wide_arprot(lfsr[53:51]),
    .wide_aruser(lfsr[54]),
    .wide_arvalid(lfsr[55]),
    .wide_rready(lfsr[56]),
    .narrow_awready(lfsr[57]),
    .narrow_wready(lfsr[58]),
    .narrow_bid(lfsr[62:59]),
    .narrow_buser(lfsr[63]),
    .narrow_bresp(lfsr[1:0]),
    .narrow_bvalid(lfsr[2]),
    .narrow_arready(lfsr[3]),
    .narrow_rid(lfsr[7:4]),
    .narrow_rdata(lfsr[39:8]),
    .narrow_ruser(lfsr[40]),
    .narrow_rresp(lfsr[42:41]),
    .narrow_rlast(lfsr[43]),
    .narrow_rvalid(lfsr[44]),
    .wide_awready(o_wide_awready),
    .wide_wready(o_wide_wready),
    .wide_bid(o_wide_bid),
    .wide_buser(o_wide_buser),
    .wide_bresp(o_wide_bresp),
    .wide_bvalid(o_wide_bvalid),
    .wide_arready(o_wide_arready),
    .wide_rid(o_wide_rid),
    .wide_rdata(o_wide_rdata),
    .wide_ruser(o_wide_ruser),
    .wide_rresp(o_wide_rresp),
    .wide_rlast(o_wide_rlast),
    .wide_rvalid(o_wide_rvalid),
    .narrow_awaddr(o_narrow_awaddr),
    .narrow_awid(o_narrow_awid),
    .narrow_awlen(o_narrow_awlen),
    .narrow_awsize(o_narrow_awsize),
    .narrow_awburst(o_narrow_awburst),
    .narrow_awprot(o_narrow_awprot),
    .narrow_awuser(o_narrow_awuser),
    .narrow_awvalid(o_narrow_awvalid),
    .narrow_wdata(o_narrow_wdata),
    .narrow_wstrb(o_narrow_wstrb),
    .narrow_wuser(o_narrow_wuser),
    .narrow_wlast(o_narrow_wlast),
    .narrow_wvalid(o_narrow_wvalid),
    .narrow_bready(o_narrow_bready),
    .narrow_araddr(o_narrow_araddr),
    .narrow_arid(o_narrow_arid),
    .narrow_arlen(o_narrow_arlen),
    .narrow_arsize(o_narrow_arsize),
    .narrow_arburst(o_narrow_arburst),
    .narrow_arprot(o_narrow_arprot),
    .narrow_aruser(o_narrow_aruser),
    .narrow_arvalid(o_narrow_arvalid),
    .narrow_rready(o_narrow_rready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
