// Generated by tools/gen_testbench.py -- lhdtrack-generated. Simulation only.
//
// Wraps br_amba_axil_timing_slice with an LFSR stimulus generator and a rotate-xor checksum, so
// every simulator compiles and runs the SAME state machine. `checksum` is the
// only thing the driver reads.
`default_nettype none

module br_amba_axil_timing_slice_harness (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] checksum
);

  logic [63:0] lfsr, sum;
  logic [63:0] nxt, acc;
  logic [0:0] o_target_awready;
  logic [0:0] o_target_wready;
  logic [1:0] o_target_bresp;
  logic [0:0] o_target_buser;
  logic [0:0] o_target_bvalid;
  logic [0:0] o_target_arready;
  logic [31:0] o_target_rdata;
  logic [1:0] o_target_rresp;
  logic [0:0] o_target_ruser;
  logic [0:0] o_target_rvalid;
  logic [31:0] o_init_awaddr;
  logic [2:0] o_init_awprot;
  logic [0:0] o_init_awuser;
  logic [0:0] o_init_awvalid;
  logic [31:0] o_init_wdata;
  logic [3:0] o_init_wstrb;
  logic [0:0] o_init_wuser;
  logic [0:0] o_init_wvalid;
  logic [0:0] o_init_bready;
  logic [31:0] o_init_araddr;
  logic [2:0] o_init_arprot;
  logic [0:0] o_init_aruser;
  logic [0:0] o_init_arvalid;
  logic [0:0] o_init_rready;

  // xorshift64 -- cheap, full-period, and trivially identical in both languages.
  always_comb begin
    nxt = lfsr ^ (lfsr << 13);
    nxt = nxt  ^ (nxt  >> 7);
    nxt = nxt  ^ (nxt  << 17);
  end

  always_comb begin
      acc = sum;
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_awready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_wready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_bresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_buser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_bvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_arready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rresp);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_ruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_target_rvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awaddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_awvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wdata);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wstrb);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wuser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_wvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_bready);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_araddr);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arprot);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_aruser);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_arvalid);
      acc = {acc[62:0], acc[63]} ^ 64'(o_init_rready);
  end

  br_amba_axil_timing_slice #(
    .AddrWidth(32),
    .DataWidth(32)
  ) dut (
    .clk(clk),
    .rst(rst),
    .target_awaddr(lfsr[31:0]),
    .target_awprot(lfsr[34:32]),
    .target_awuser(lfsr[35]),
    .target_awvalid(lfsr[36]),
    .target_wdata({5'd0, lfsr[63:37]}),
    .target_wstrb(lfsr[8:5]),
    .target_wuser(lfsr[9]),
    .target_wvalid(lfsr[10]),
    .target_bready(lfsr[11]),
    .target_araddr(lfsr[43:12]),
    .target_arprot(lfsr[46:44]),
    .target_aruser(lfsr[47]),
    .target_arvalid(lfsr[48]),
    .target_rready(lfsr[49]),
    .init_awready(lfsr[50]),
    .init_wready(lfsr[51]),
    .init_bresp(lfsr[53:52]),
    .init_buser(lfsr[54]),
    .init_bvalid(lfsr[55]),
    .init_arready(lfsr[56]),
    .init_rdata({25'd0, lfsr[63:57]}),
    .init_rresp(lfsr[26:25]),
    .init_ruser(lfsr[27]),
    .init_rvalid(lfsr[28]),
    .target_awready(o_target_awready),
    .target_wready(o_target_wready),
    .target_bresp(o_target_bresp),
    .target_buser(o_target_buser),
    .target_bvalid(o_target_bvalid),
    .target_arready(o_target_arready),
    .target_rdata(o_target_rdata),
    .target_rresp(o_target_rresp),
    .target_ruser(o_target_ruser),
    .target_rvalid(o_target_rvalid),
    .init_awaddr(o_init_awaddr),
    .init_awprot(o_init_awprot),
    .init_awuser(o_init_awuser),
    .init_awvalid(o_init_awvalid),
    .init_wdata(o_init_wdata),
    .init_wstrb(o_init_wstrb),
    .init_wuser(o_init_wuser),
    .init_wvalid(o_init_wvalid),
    .init_bready(o_init_bready),
    .init_araddr(o_init_araddr),
    .init_arprot(o_init_arprot),
    .init_aruser(o_init_aruser),
    .init_arvalid(o_init_arvalid),
    .init_rready(o_init_rready)
  );

  always_ff @(posedge clk) begin
    if (rst) begin
      lfsr <= 64'd2611923443488327891;
      sum  <= 64'd0;
    end else begin
      lfsr <= nxt;
      sum  <= acc;
    end
  end

  assign checksum = sum;

endmodule

`default_nettype wire
